/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * GetRedisServiceSpecReq
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GetRedisServiceSpecReq {
  public static final String SERIALIZED_NAME_LABELS = "Labels";
  @SerializedName(SERIALIZED_NAME_LABELS)
  private Map<String, String> labels = new HashMap<>();

  public static final String SERIALIZED_NAME_REDIS_CONTAINER_PORT = "RedisContainerPort";
  @SerializedName(SERIALIZED_NAME_REDIS_CONTAINER_PORT)
  private Integer redisContainerPort;

  public static final String SERIALIZED_NAME_SENTINEL_CONTAINER_PORT = "SentinelContainerPort";
  @SerializedName(SERIALIZED_NAME_SENTINEL_CONTAINER_PORT)
  private Integer sentinelContainerPort;


  public GetRedisServiceSpecReq labels(Map<String, String> labels) {
    
    this.labels = labels;
    return this;
  }

  public GetRedisServiceSpecReq putLabelsItem(String key, String labelsItem) {
    this.labels.put(key, labelsItem);
    return this;
  }

   /**
   * Get labels
   * @return labels
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Map<String, String> getLabels() {
    return labels;
  }


  public void setLabels(Map<String, String> labels) {
    this.labels = labels;
  }


  public GetRedisServiceSpecReq redisContainerPort(Integer redisContainerPort) {
    
    this.redisContainerPort = redisContainerPort;
    return this;
  }

   /**
   * Get redisContainerPort
   * @return redisContainerPort
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getRedisContainerPort() {
    return redisContainerPort;
  }


  public void setRedisContainerPort(Integer redisContainerPort) {
    this.redisContainerPort = redisContainerPort;
  }


  public GetRedisServiceSpecReq sentinelContainerPort(Integer sentinelContainerPort) {
    
    this.sentinelContainerPort = sentinelContainerPort;
    return this;
  }

   /**
   * Get sentinelContainerPort
   * @return sentinelContainerPort
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getSentinelContainerPort() {
    return sentinelContainerPort;
  }


  public void setSentinelContainerPort(Integer sentinelContainerPort) {
    this.sentinelContainerPort = sentinelContainerPort;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetRedisServiceSpecReq getRedisServiceSpecReq = (GetRedisServiceSpecReq) o;
    return Objects.equals(this.labels, getRedisServiceSpecReq.labels) &&
        Objects.equals(this.redisContainerPort, getRedisServiceSpecReq.redisContainerPort) &&
        Objects.equals(this.sentinelContainerPort, getRedisServiceSpecReq.sentinelContainerPort);
  }

  @Override
  public int hashCode() {
    return Objects.hash(labels, redisContainerPort, sentinelContainerPort);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetRedisServiceSpecReq {\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    redisContainerPort: ").append(toIndentedString(redisContainerPort)).append("\n");
    sb.append("    sentinelContainerPort: ").append(toIndentedString(sentinelContainerPort)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

