/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.openapi.models.V1SecretKeySelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TLS
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TLS {
  public static final String SERIALIZED_NAME_CA_CERT_SECRET = "caCertSecret";
  @SerializedName(SERIALIZED_NAME_CA_CERT_SECRET)
  private V1SecretKeySelector caCertSecret = null;

  public static final String SERIALIZED_NAME_CLIENT_CERT_SECRET = "clientCertSecret";
  @SerializedName(SERIALIZED_NAME_CLIENT_CERT_SECRET)
  private V1SecretKeySelector clientCertSecret = null;

  public static final String SERIALIZED_NAME_CLIENT_KEY_SECRET = "clientKeySecret";
  @SerializedName(SERIALIZED_NAME_CLIENT_KEY_SECRET)
  private V1SecretKeySelector clientKeySecret = null;

  public static final String SERIALIZED_NAME_INSECURE_SKIP_VERIFY = "insecureSkipVerify";
  @SerializedName(SERIALIZED_NAME_INSECURE_SKIP_VERIFY)
  private Boolean insecureSkipVerify;


  public TLS caCertSecret(V1SecretKeySelector caCertSecret) {
    
    this.caCertSecret = caCertSecret;
    return this;
  }

   /**
   * Get caCertSecret
   * @return caCertSecret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1SecretKeySelector getCaCertSecret() {
    return caCertSecret;
  }


  public void setCaCertSecret(V1SecretKeySelector caCertSecret) {
    this.caCertSecret = caCertSecret;
  }


  public TLS clientCertSecret(V1SecretKeySelector clientCertSecret) {
    
    this.clientCertSecret = clientCertSecret;
    return this;
  }

   /**
   * Get clientCertSecret
   * @return clientCertSecret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1SecretKeySelector getClientCertSecret() {
    return clientCertSecret;
  }


  public void setClientCertSecret(V1SecretKeySelector clientCertSecret) {
    this.clientCertSecret = clientCertSecret;
  }


  public TLS clientKeySecret(V1SecretKeySelector clientKeySecret) {
    
    this.clientKeySecret = clientKeySecret;
    return this;
  }

   /**
   * Get clientKeySecret
   * @return clientKeySecret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1SecretKeySelector getClientKeySecret() {
    return clientKeySecret;
  }


  public void setClientKeySecret(V1SecretKeySelector clientKeySecret) {
    this.clientKeySecret = clientKeySecret;
  }


  public TLS insecureSkipVerify(Boolean insecureSkipVerify) {
    
    this.insecureSkipVerify = insecureSkipVerify;
    return this;
  }

   /**
   * Get insecureSkipVerify
   * @return insecureSkipVerify
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getInsecureSkipVerify() {
    return insecureSkipVerify;
  }


  public void setInsecureSkipVerify(Boolean insecureSkipVerify) {
    this.insecureSkipVerify = insecureSkipVerify;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TLS TLS = (TLS) o;
    return Objects.equals(this.caCertSecret, TLS.caCertSecret) &&
        Objects.equals(this.clientCertSecret, TLS.clientCertSecret) &&
        Objects.equals(this.clientKeySecret, TLS.clientKeySecret) &&
        Objects.equals(this.insecureSkipVerify, TLS.insecureSkipVerify);
  }

  @Override
  public int hashCode() {
    return Objects.hash(caCertSecret, clientCertSecret, clientKeySecret, insecureSkipVerify);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TLS {\n");
    sb.append("    caCertSecret: ").append(toIndentedString(caCertSecret)).append("\n");
    sb.append("    clientCertSecret: ").append(toIndentedString(clientCertSecret)).append("\n");
    sb.append("    clientKeySecret: ").append(toIndentedString(clientKeySecret)).append("\n");
    sb.append("    insecureSkipVerify: ").append(toIndentedString(insecureSkipVerify)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

