apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: numaflow-dex-server
    app.kubernetes.io/part-of: numaflow
    app.kubernetes.io/component: dex-server
  name: numaflow-dex-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: numaflow-dex-server
subjects:
  - kind: ServiceAccount
    name: numaflow-dex-server