apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: numaflow-dex-server
    app.kubernetes.io/part-of: numaflow
    app.kubernetes.io/component: dex-server
  name: numaflow-dex-server
