tid_header = "ID"
app_listen_port = 3000
metrics_server_listen_port = 3001
upstream_addr = "localhost:8888"
drain_timeout_secs = 10
host_ip = "localhost"

[jetstream]
stream = "default"
url = "localhost:4222"

[redis]
addr = "redis://127.0.0.1/"
max_tasks = 50
retries = 5
retries_duration_millis = 100
ttl_secs = 1
