/*
Copyright 2022 The Numaproj Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Openapi Generator. DO NOT EDIT.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CronSchedule {
    /// End of the cron window. Same format as Start. Must differ from Start.
    #[serde(rename = "end")]
    pub end: String,
    /// Maximum replicas during this window. Overrides scale.max.
    #[serde(rename = "max")]
    pub max: i32,
    /// Minimum replicas during this window. Overrides scale.min.
    #[serde(rename = "min")]
    pub min: i32,
    /// Start of the cron window. Linux cron format (Minute Hour Dom Month Dow).
    #[serde(rename = "start")]
    pub start: String,
}

impl CronSchedule {
    pub fn new(end: String, max: i32, min: i32, start: String) -> CronSchedule {
        CronSchedule {
            end,
            max,
            min,
            start,
        }
    }
}
