/*
Copyright 2022 The Numaproj Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Openapi Generator. DO NOT EDIT.

/// CronScheduling : CronScheduling defines cron-based autoscaling overrides.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CronScheduling {
    /// Schedules are evaluated in order; the first active schedule takes precedence when windows overlap.
    #[serde(rename = "schedules")]
    pub schedules: Vec<crate::models::CronSchedule>,
    /// Timezone for interpreting cron expressions. IANA Time Zone Database format. Defaults to UTC.
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
}

impl CronScheduling {
    /// CronScheduling defines cron-based autoscaling overrides.
    pub fn new(schedules: Vec<crate::models::CronSchedule>) -> CronScheduling {
        CronScheduling {
            schedules,
            timezone: None,
        }
    }
}
