/*
Copyright 2022 The Numaproj Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Openapi Generator. DO NOT EDIT.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonoVertexSinkerCondition {
    #[serde(rename = "fallback", skip_serializing_if = "Option::is_none")]
    pub fallback: Option<Box<crate::models::ForwardConditions>>,
    #[serde(rename = "onSuccess", skip_serializing_if = "Option::is_none")]
    pub on_success: Option<Box<crate::models::ForwardConditions>>,
    #[serde(rename = "sink", skip_serializing_if = "Option::is_none")]
    pub sink: Option<Box<crate::models::ForwardConditions>>,
}

impl MonoVertexSinkerCondition {
    pub fn new() -> MonoVertexSinkerCondition {
        MonoVertexSinkerCondition {
            fallback: None,
            on_success: None,
            sink: None,
        }
    }
}
