/*
Copyright 2022 The Numaproj Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Openapi Generator. DO NOT EDIT.

/// PulsarAuth : PulsarAuth defines how to authenticate with Pulsar

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PulsarAuth {
    #[serde(rename = "basicAuth", skip_serializing_if = "Option::is_none")]
    pub basic_auth: Option<Box<crate::models::PulsarBasicAuth>>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<k8s_openapi::api::core::v1::SecretKeySelector>,
}

impl PulsarAuth {
    /// PulsarAuth defines how to authenticate with Pulsar
    pub fn new() -> PulsarAuth {
        PulsarAuth {
            basic_auth: None,
            token: None,
        }
    }
}
