ignore:
- "**/*.pb.go"
- "**/*.pb.gw.go"
- "**/*generated.go"
- "**/*generated.deepcopy.go"
- "**/*generated.openapi.go"
- "**/*_test.go"
- "pkg/client/.*"
- "vendor/.*"
- "test/.*"
- "rust/**/error.rs"
- "rust/numaflow-models/**" # ignore generated files
coverage:
  status:
    patch: off
    project:
      default:
        # allow test coverage to drop by 2%, assume that it's typically due to CI problems
        threshold: 2
