apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: numaflow-server-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: numaflow-server-role
subjects:
  - kind: ServiceAccount
    name: numaflow-server-sa
    namespace: numaflow-system