apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- https://raw.githubusercontent.com/numaproj/numaflow/main/docs/user-guide/kustomize/numaflow-transformer-config.yaml

namePrefix: my-

resources:
- my-pipeline.yaml

configMapGenerator:
- name: my-cm
  literals:
  - FOO=BAR

secretGenerator:
- name: my-secret
  literals:
  - password=Pa5SW0rD

commonLabels:
  foo: bar

commonAnnotations:
  foo: bar

images:
- name: my-pipeline/my-udf
  newTag: my-version
