// This file is @generated by prost-build.
/// Payload that represent the output that is to be written into to the store.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Payload {
    /// Origin is the Vertex that generated this result.
    #[prost(string, tag = "1")]
    pub origin: ::prost::alloc::string::String,
    /// Value is the result of the computation.
    #[prost(bytes = "vec", tag = "2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
/// PutRequest is the request sent to the Store.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PutRequest {
    /// ID is the unique id as provided by the user in the original request. If not provided, it will be a system generated
    /// uuid.
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Payloads are one or more results generated (could be more than one due to flat-map).
    #[prost(message, repeated, tag = "2")]
    pub payloads: ::prost::alloc::vec::Vec<Payload>,
}
/// PutResponse is the result of the Put call.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PutResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
/// GetRequest is the call to get the result stored in the Store.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetRequest {
    /// ID is the unique id as provided by the user in the original request. If not provided, it will be a system generated
    /// uuid.
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
/// GetResponse is the result stored in the Store.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetResponse {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Payloads are one or more results generated (could be more than one due to flat-map).
    #[prost(message, repeated, tag = "2")]
    pub payloads: ::prost::alloc::vec::Vec<Payload>,
}
/// *
///
/// ReadyResponse is the health check result.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadyResponse {
    #[prost(bool, tag = "1")]
    pub ready: bool,
}
/// Generated client implementations.
pub mod serving_store_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// ServingStore defines a set of methods to interface with a user-defined Store.
    #[derive(Debug, Clone)]
    pub struct ServingStoreClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ServingStoreClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ServingStoreClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ServingStoreClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ServingStoreClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Put is to put the PutRequest into the Store.
        pub async fn put(
            &mut self,
            request: impl tonic::IntoRequest<super::PutRequest>,
        ) -> std::result::Result<tonic::Response<super::PutResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/serving.v1.ServingStore/Put",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("serving.v1.ServingStore", "Put"));
            self.inner.unary(req, path, codec).await
        }
        /// Get gets the GetRequest from the Store.
        pub async fn get(
            &mut self,
            request: impl tonic::IntoRequest<super::GetRequest>,
        ) -> std::result::Result<tonic::Response<super::GetResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/serving.v1.ServingStore/Get",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("serving.v1.ServingStore", "Get"));
            self.inner.unary(req, path, codec).await
        }
        /// IsReady checks the health of the container interfacing the Store.
        pub async fn is_ready(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> std::result::Result<tonic::Response<super::ReadyResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/serving.v1.ServingStore/IsReady",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("serving.v1.ServingStore", "IsReady"));
            self.inner.unary(req, path, codec).await
        }
    }
}
