// This file is @generated by prost-build.
/// KeyedWindow represents a window with keys.
/// since the client track the keys, we use keyed window.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KeyedWindow {
    #[prost(message, optional, tag = "1")]
    pub start: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "2")]
    pub end: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "3")]
    pub slot: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// SessionReduceRequest represents a request element.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionReduceRequest {
    #[prost(message, optional, tag = "1")]
    pub payload: ::core::option::Option<session_reduce_request::Payload>,
    #[prost(message, optional, tag = "2")]
    pub operation: ::core::option::Option<session_reduce_request::WindowOperation>,
}
/// Nested message and enum types in `SessionReduceRequest`.
pub mod session_reduce_request {
    /// WindowOperation represents a window operation.
    /// For Aligned window values can be one of OPEN, CLOSE, EXPAND, MERGE and APPEND.
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct WindowOperation {
        #[prost(enumeration = "window_operation::Event", tag = "1")]
        pub event: i32,
        #[prost(message, repeated, tag = "2")]
        pub keyed_windows: ::prost::alloc::vec::Vec<super::KeyedWindow>,
    }
    /// Nested message and enum types in `WindowOperation`.
    pub mod window_operation {
        #[derive(
            Clone,
            Copy,
            Debug,
            PartialEq,
            Eq,
            Hash,
            PartialOrd,
            Ord,
            ::prost::Enumeration
        )]
        #[repr(i32)]
        pub enum Event {
            Open = 0,
            Close = 1,
            Expand = 2,
            Merge = 3,
            Append = 4,
        }
        impl Event {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::Open => "OPEN",
                    Self::Close => "CLOSE",
                    Self::Expand => "EXPAND",
                    Self::Merge => "MERGE",
                    Self::Append => "APPEND",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "OPEN" => Some(Self::Open),
                    "CLOSE" => Some(Self::Close),
                    "EXPAND" => Some(Self::Expand),
                    "MERGE" => Some(Self::Merge),
                    "APPEND" => Some(Self::Append),
                    _ => None,
                }
            }
        }
    }
    /// Payload represents a payload element.
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Payload {
        #[prost(string, repeated, tag = "1")]
        pub keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
        #[prost(bytes = "vec", tag = "2")]
        pub value: ::prost::alloc::vec::Vec<u8>,
        #[prost(message, optional, tag = "3")]
        pub event_time: ::core::option::Option<::prost_types::Timestamp>,
        #[prost(message, optional, tag = "4")]
        pub watermark: ::core::option::Option<::prost_types::Timestamp>,
        #[prost(map = "string, string", tag = "5")]
        pub headers: ::std::collections::HashMap<
            ::prost::alloc::string::String,
            ::prost::alloc::string::String,
        >,
        /// Metadata is the metadata of the message
        #[prost(message, optional, tag = "6")]
        pub metadata: ::core::option::Option<crate::common::metadata::Metadata>,
    }
}
/// SessionReduceResponse represents a response element.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionReduceResponse {
    #[prost(message, optional, tag = "1")]
    pub result: ::core::option::Option<session_reduce_response::Result>,
    /// keyedWindow represents a window to which the result belongs.
    #[prost(message, optional, tag = "2")]
    pub keyed_window: ::core::option::Option<KeyedWindow>,
    /// EOF represents the end of the response for a window.
    #[prost(bool, tag = "3")]
    pub eof: bool,
}
/// Nested message and enum types in `SessionReduceResponse`.
pub mod session_reduce_response {
    /// Result represents a result element. It contains the result of the reduce function.
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Result {
        #[prost(string, repeated, tag = "1")]
        pub keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
        #[prost(bytes = "vec", tag = "2")]
        pub value: ::prost::alloc::vec::Vec<u8>,
        #[prost(string, repeated, tag = "3")]
        pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
        /// Metadata is the metadata of the message
        #[prost(message, optional, tag = "4")]
        pub metadata: ::core::option::Option<crate::common::metadata::Metadata>,
    }
}
/// ReadyResponse is the health check result.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadyResponse {
    #[prost(bool, tag = "1")]
    pub ready: bool,
}
/// Generated client implementations.
pub mod session_reduce_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct SessionReduceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl SessionReduceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> SessionReduceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> SessionReduceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            SessionReduceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// SessionReduceFn applies a reduce function to a request stream.
        pub async fn session_reduce_fn(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::SessionReduceRequest,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::SessionReduceResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sessionreduce.v1.SessionReduce/SessionReduceFn",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("sessionreduce.v1.SessionReduce", "SessionReduceFn"),
                );
            self.inner.streaming(req, path, codec).await
        }
        /// IsReady is the heartbeat endpoint for gRPC.
        pub async fn is_ready(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> std::result::Result<tonic::Response<super::ReadyResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sessionreduce.v1.SessionReduce/IsReady",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("sessionreduce.v1.SessionReduce", "IsReady"));
            self.inner.unary(req, path, codec).await
        }
    }
}
