//
//Copyright 2022 The Numaproj Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: pkg/apis/proto/wmb/wmb.proto

package isb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WMB is used in the KV offset timeline bucket as the value for the given processor entity key.
type WMB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Idle is set to true if the given processor entity hasn't published anything
	// to the offset timeline bucket in a batch processing cycle.
	// Idle is used to signal an idle watermark.
	Idle bool `protobuf:"varint,1,opt,name=idle,proto3" json:"idle,omitempty"`
	// Offset is the monotonically increasing index/offset of the buffer (buffer is the physical representation
	// of the partition of the edge).
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Watermark is tightly coupled with the offset and will be monotonically increasing for a given ProcessorEntity
	// as the offset increases.
	// When it is idling (Idle==true), for a given offset, the watermark can monotonically increase without offset
	// increasing.
	Watermark int64 `protobuf:"varint,3,opt,name=watermark,proto3" json:"watermark,omitempty"`
	// Partition to identify the partition to which the watermark belongs.
	Partition int32 `protobuf:"varint,4,opt,name=partition,proto3" json:"partition,omitempty"`
}

func (x *WMB) Reset() {
	*x = WMB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_proto_wmb_wmb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WMB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WMB) ProtoMessage() {}

func (x *WMB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_wmb_wmb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WMB.ProtoReflect.Descriptor instead.
func (*WMB) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_wmb_wmb_proto_rawDescGZIP(), []int{0}
}

func (x *WMB) GetIdle() bool {
	if x != nil {
		return x.Idle
	}
	return false
}

func (x *WMB) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WMB) GetWatermark() int64 {
	if x != nil {
		return x.Watermark
	}
	return 0
}

func (x *WMB) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

var File_pkg_apis_proto_wmb_wmb_proto protoreflect.FileDescriptor

var file_pkg_apis_proto_wmb_wmb_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x77, 0x6d, 0x62, 0x2f, 0x77, 0x6d, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x77, 0x6d, 0x62, 0x22, 0x6d, 0x0a, 0x03, 0x57, 0x4d, 0x42, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x64,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x77, 0x61, 0x74, 0x65, 0x72, 0x6d,
	0x61, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x77, 0x61, 0x74, 0x65, 0x72,
	0x6d, 0x61, 0x72, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6e, 0x75, 0x6d, 0x61, 0x70, 0x72, 0x6f, 0x6a, 0x2f, 0x6e, 0x75, 0x6d, 0x61, 0x66, 0x6c,
	0x6f, 0x77, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x69, 0x73, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_apis_proto_wmb_wmb_proto_rawDescOnce sync.Once
	file_pkg_apis_proto_wmb_wmb_proto_rawDescData = file_pkg_apis_proto_wmb_wmb_proto_rawDesc
)

func file_pkg_apis_proto_wmb_wmb_proto_rawDescGZIP() []byte {
	file_pkg_apis_proto_wmb_wmb_proto_rawDescOnce.Do(func() {
		file_pkg_apis_proto_wmb_wmb_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_apis_proto_wmb_wmb_proto_rawDescData)
	})
	return file_pkg_apis_proto_wmb_wmb_proto_rawDescData
}

var file_pkg_apis_proto_wmb_wmb_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_apis_proto_wmb_wmb_proto_goTypes = []any{
	(*WMB)(nil), // 0: wmb.WMB
}
var file_pkg_apis_proto_wmb_wmb_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_apis_proto_wmb_wmb_proto_init() }
func file_pkg_apis_proto_wmb_wmb_proto_init() {
	if File_pkg_apis_proto_wmb_wmb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_apis_proto_wmb_wmb_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*WMB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_apis_proto_wmb_wmb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_apis_proto_wmb_wmb_proto_goTypes,
		DependencyIndexes: file_pkg_apis_proto_wmb_wmb_proto_depIdxs,
		MessageInfos:      file_pkg_apis_proto_wmb_wmb_proto_msgTypes,
	}.Build()
	File_pkg_apis_proto_wmb_wmb_proto = out.File
	file_pkg_apis_proto_wmb_wmb_proto_rawDesc = nil
	file_pkg_apis_proto_wmb_wmb_proto_goTypes = nil
	file_pkg_apis_proto_wmb_wmb_proto_depIdxs = nil
}
