/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetRedisServiceSpecReq
 */
public class GetRedisServiceSpecReqTest {
    private final GetRedisServiceSpecReq model = new GetRedisServiceSpecReq();

    /**
     * Model tests for GetRedisServiceSpecReq
     */
    @Test
    public void testGetRedisServiceSpecReq() {
        // TODO: test GetRedisServiceSpecReq
    }

    /**
     * Test the property 'labels'
     */
    @Test
    public void labelsTest() {
        // TODO: test labels
    }

    /**
     * Test the property 'redisContainerPort'
     */
    @Test
    public void redisContainerPortTest() {
        // TODO: test redisContainerPort
    }

    /**
     * Test the property 'sentinelContainerPort'
     */
    @Test
    public void sentinelContainerPortTest() {
        // TODO: test sentinelContainerPort
    }

}
