/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.numaproj.numaflow.models.JetStreamBufferService;
import io.numaproj.numaflow.models.RedisBuferService;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InterStepBufferServiceSpec
 */
public class InterStepBufferServiceSpecTest {
    private final InterStepBufferServiceSpec model = new InterStepBufferServiceSpec();

    /**
     * Model tests for InterStepBufferServiceSpec
     */
    @Test
    public void testInterStepBufferServiceSpec() {
        // TODO: test InterStepBufferServiceSpec
    }

    /**
     * Test the property 'jetstream'
     */
    @Test
    public void jetstreamTest() {
        // TODO: test jetstream
    }

    /**
     * Test the property 'redis'
     */
    @Test
    public void redisTest() {
        // TODO: test redis
    }

}
