/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.numaproj.numaflow.models.NATSAuth;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for JetStreamConfig
 */
public class JetStreamConfigTest {
    private final JetStreamConfig model = new JetStreamConfig();

    /**
     * Model tests for JetStreamConfig
     */
    @Test
    public void testJetStreamConfig() {
        // TODO: test JetStreamConfig
    }

    /**
     * Test the property 'auth'
     */
    @Test
    public void authTest() {
        // TODO: test auth
    }

    /**
     * Test the property 'bufferConfig'
     */
    @Test
    public void bufferConfigTest() {
        // TODO: test bufferConfig
    }

    /**
     * Test the property 'tlsEnabled'
     */
    @Test
    public void tlsEnabledTest() {
        // TODO: test tlsEnabled
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

}
