/*
 * Numaflow
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.numaproj.numaflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.Duration;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VertexLimits
 */
public class VertexLimitsTest {
    private final VertexLimits model = new VertexLimits();

    /**
     * Model tests for VertexLimits
     */
    @Test
    public void testVertexLimits() {
        // TODO: test VertexLimits
    }

    /**
     * Test the property 'readBatchSize'
     */
    @Test
    public void readBatchSizeTest() {
        // TODO: test readBatchSize
    }

    /**
     * Test the property 'readTimeout'
     */
    @Test
    public void readTimeoutTest() {
        // TODO: test readTimeout
    }

}
