//
//Copyright 2022 The Numaproj Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.27.2
// source: pkg/apis/proto/daemon/daemon.proto

package daemon

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BufferInfo is used to provide information about the buffer including
// pending messages count, if it has unprocessed data etc which helps in pipeline/buffer deletion etc
type BufferInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Pipeline        string                 `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	BufferName      string                 `protobuf:"bytes,2,opt,name=bufferName,proto3" json:"bufferName,omitempty"`
	PendingCount    *wrapperspb.Int64Value `protobuf:"bytes,3,opt,name=pendingCount,proto3" json:"pendingCount,omitempty"`
	AckPendingCount *wrapperspb.Int64Value `protobuf:"bytes,4,opt,name=ackPendingCount,proto3" json:"ackPendingCount,omitempty"`
	// Total messages existing in the buffer, including pending, ackPending and acked.
	// Using Int64Value to solve the problem of int64 in proto3 being serialized to string when converting to JSON.
	TotalMessages    *wrapperspb.Int64Value  `protobuf:"bytes,5,opt,name=totalMessages,proto3" json:"totalMessages,omitempty"`
	BufferLength     *wrapperspb.Int64Value  `protobuf:"bytes,6,opt,name=bufferLength,proto3" json:"bufferLength,omitempty"`
	BufferUsageLimit *wrapperspb.DoubleValue `protobuf:"bytes,7,opt,name=bufferUsageLimit,proto3" json:"bufferUsageLimit,omitempty"`
	BufferUsage      *wrapperspb.DoubleValue `protobuf:"bytes,8,opt,name=bufferUsage,proto3" json:"bufferUsage,omitempty"`
	IsFull           *wrapperspb.BoolValue   `protobuf:"bytes,9,opt,name=isFull,proto3" json:"isFull,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BufferInfo) Reset() {
	*x = BufferInfo{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferInfo) ProtoMessage() {}

func (x *BufferInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferInfo.ProtoReflect.Descriptor instead.
func (*BufferInfo) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *BufferInfo) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

func (x *BufferInfo) GetBufferName() string {
	if x != nil {
		return x.BufferName
	}
	return ""
}

func (x *BufferInfo) GetPendingCount() *wrapperspb.Int64Value {
	if x != nil {
		return x.PendingCount
	}
	return nil
}

func (x *BufferInfo) GetAckPendingCount() *wrapperspb.Int64Value {
	if x != nil {
		return x.AckPendingCount
	}
	return nil
}

func (x *BufferInfo) GetTotalMessages() *wrapperspb.Int64Value {
	if x != nil {
		return x.TotalMessages
	}
	return nil
}

func (x *BufferInfo) GetBufferLength() *wrapperspb.Int64Value {
	if x != nil {
		return x.BufferLength
	}
	return nil
}

func (x *BufferInfo) GetBufferUsageLimit() *wrapperspb.DoubleValue {
	if x != nil {
		return x.BufferUsageLimit
	}
	return nil
}

func (x *BufferInfo) GetBufferUsage() *wrapperspb.DoubleValue {
	if x != nil {
		return x.BufferUsage
	}
	return nil
}

func (x *BufferInfo) GetIsFull() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsFull
	}
	return nil
}

// VertexMetrics is used to provide information about the vertex including processing rate.
type VertexMetrics struct {
	state           protoimpl.MessageState             `protogen:"open.v1"`
	Pipeline        string                             `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Vertex          string                             `protobuf:"bytes,2,opt,name=vertex,proto3" json:"vertex,omitempty"`
	ProcessingRates map[string]*wrapperspb.DoubleValue `protobuf:"bytes,3,rep,name=processingRates,proto3" json:"processingRates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Pendings        map[string]*wrapperspb.Int64Value  `protobuf:"bytes,4,rep,name=pendings,proto3" json:"pendings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VertexMetrics) Reset() {
	*x = VertexMetrics{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VertexMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VertexMetrics) ProtoMessage() {}

func (x *VertexMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VertexMetrics.ProtoReflect.Descriptor instead.
func (*VertexMetrics) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *VertexMetrics) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

func (x *VertexMetrics) GetVertex() string {
	if x != nil {
		return x.Vertex
	}
	return ""
}

func (x *VertexMetrics) GetProcessingRates() map[string]*wrapperspb.DoubleValue {
	if x != nil {
		return x.ProcessingRates
	}
	return nil
}

func (x *VertexMetrics) GetPendings() map[string]*wrapperspb.Int64Value {
	if x != nil {
		return x.Pendings
	}
	return nil
}

// PipelineStatus
type PipelineStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineStatus) Reset() {
	*x = PipelineStatus{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineStatus) ProtoMessage() {}

func (x *PipelineStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineStatus.ProtoReflect.Descriptor instead.
func (*PipelineStatus) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *PipelineStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PipelineStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PipelineStatus) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ListBuffersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipeline      string                 `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuffersRequest) Reset() {
	*x = ListBuffersRequest{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuffersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuffersRequest) ProtoMessage() {}

func (x *ListBuffersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuffersRequest.ProtoReflect.Descriptor instead.
func (*ListBuffersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *ListBuffersRequest) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

type ListBuffersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buffers       []*BufferInfo          `protobuf:"bytes,1,rep,name=buffers,proto3" json:"buffers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuffersResponse) Reset() {
	*x = ListBuffersResponse{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuffersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuffersResponse) ProtoMessage() {}

func (x *ListBuffersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuffersResponse.ProtoReflect.Descriptor instead.
func (*ListBuffersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *ListBuffersResponse) GetBuffers() []*BufferInfo {
	if x != nil {
		return x.Buffers
	}
	return nil
}

type GetBufferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipeline      string                 `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Buffer        string                 `protobuf:"bytes,2,opt,name=buffer,proto3" json:"buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBufferRequest) Reset() {
	*x = GetBufferRequest{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBufferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBufferRequest) ProtoMessage() {}

func (x *GetBufferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBufferRequest.ProtoReflect.Descriptor instead.
func (*GetBufferRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *GetBufferRequest) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

func (x *GetBufferRequest) GetBuffer() string {
	if x != nil {
		return x.Buffer
	}
	return ""
}

type GetBufferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buffer        *BufferInfo            `protobuf:"bytes,1,opt,name=buffer,proto3" json:"buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBufferResponse) Reset() {
	*x = GetBufferResponse{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBufferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBufferResponse) ProtoMessage() {}

func (x *GetBufferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBufferResponse.ProtoReflect.Descriptor instead.
func (*GetBufferResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *GetBufferResponse) GetBuffer() *BufferInfo {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type GetPipelineStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipeline      string                 `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineStatusRequest) Reset() {
	*x = GetPipelineStatusRequest{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineStatusRequest) ProtoMessage() {}

func (x *GetPipelineStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPipelineStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *GetPipelineStatusRequest) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

type GetPipelineStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *PipelineStatus        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineStatusResponse) Reset() {
	*x = GetPipelineStatusResponse{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineStatusResponse) ProtoMessage() {}

func (x *GetPipelineStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPipelineStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *GetPipelineStatusResponse) GetStatus() *PipelineStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetVertexMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipeline      string                 `protobuf:"bytes,2,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Vertex        string                 `protobuf:"bytes,3,opt,name=vertex,proto3" json:"vertex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVertexMetricsRequest) Reset() {
	*x = GetVertexMetricsRequest{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVertexMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVertexMetricsRequest) ProtoMessage() {}

func (x *GetVertexMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVertexMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetVertexMetricsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *GetVertexMetricsRequest) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

func (x *GetVertexMetricsRequest) GetVertex() string {
	if x != nil {
		return x.Vertex
	}
	return ""
}

type GetVertexMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VertexMetrics []*VertexMetrics       `protobuf:"bytes,1,rep,name=vertexMetrics,proto3" json:"vertexMetrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVertexMetricsResponse) Reset() {
	*x = GetVertexMetricsResponse{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVertexMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVertexMetricsResponse) ProtoMessage() {}

func (x *GetVertexMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVertexMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetVertexMetricsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *GetVertexMetricsResponse) GetVertexMetrics() []*VertexMetrics {
	if x != nil {
		return x.VertexMetrics
	}
	return nil
}

// EdgeWatermark has edge to watermark mapping.
type EdgeWatermark struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	Pipeline           string                   `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Edge               string                   `protobuf:"bytes,2,opt,name=edge,proto3" json:"edge,omitempty"`
	Watermarks         []*wrapperspb.Int64Value `protobuf:"bytes,3,rep,name=watermarks,proto3" json:"watermarks,omitempty"`
	IsWatermarkEnabled *wrapperspb.BoolValue    `protobuf:"bytes,4,opt,name=isWatermarkEnabled,proto3" json:"isWatermarkEnabled,omitempty"`
	From               string                   `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To                 string                   `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EdgeWatermark) Reset() {
	*x = EdgeWatermark{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeWatermark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeWatermark) ProtoMessage() {}

func (x *EdgeWatermark) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeWatermark.ProtoReflect.Descriptor instead.
func (*EdgeWatermark) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *EdgeWatermark) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

func (x *EdgeWatermark) GetEdge() string {
	if x != nil {
		return x.Edge
	}
	return ""
}

func (x *EdgeWatermark) GetWatermarks() []*wrapperspb.Int64Value {
	if x != nil {
		return x.Watermarks
	}
	return nil
}

func (x *EdgeWatermark) GetIsWatermarkEnabled() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsWatermarkEnabled
	}
	return nil
}

func (x *EdgeWatermark) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *EdgeWatermark) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type GetPipelineWatermarksResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PipelineWatermarks []*EdgeWatermark       `protobuf:"bytes,1,rep,name=pipelineWatermarks,proto3" json:"pipelineWatermarks,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetPipelineWatermarksResponse) Reset() {
	*x = GetPipelineWatermarksResponse{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineWatermarksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineWatermarksResponse) ProtoMessage() {}

func (x *GetPipelineWatermarksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineWatermarksResponse.ProtoReflect.Descriptor instead.
func (*GetPipelineWatermarksResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *GetPipelineWatermarksResponse) GetPipelineWatermarks() []*EdgeWatermark {
	if x != nil {
		return x.PipelineWatermarks
	}
	return nil
}

// GetPipelineWatermarksRequest requests for the watermark for a pipeline.
type GetPipelineWatermarksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipeline      string                 `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineWatermarksRequest) Reset() {
	*x = GetPipelineWatermarksRequest{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineWatermarksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineWatermarksRequest) ProtoMessage() {}

func (x *GetPipelineWatermarksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineWatermarksRequest.ProtoReflect.Descriptor instead.
func (*GetPipelineWatermarksRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *GetPipelineWatermarksRequest) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

// GetVertexErrorsRequest is a request message for retrieving the errors for a vertex.
type GetVertexErrorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipeline      string                 `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Vertex        string                 `protobuf:"bytes,2,opt,name=vertex,proto3" json:"vertex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVertexErrorsRequest) Reset() {
	*x = GetVertexErrorsRequest{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVertexErrorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVertexErrorsRequest) ProtoMessage() {}

func (x *GetVertexErrorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVertexErrorsRequest.ProtoReflect.Descriptor instead.
func (*GetVertexErrorsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{14}
}

func (x *GetVertexErrorsRequest) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

func (x *GetVertexErrorsRequest) GetVertex() string {
	if x != nil {
		return x.Vertex
	}
	return ""
}

// ContainerError is used to provide information for a container error
// including timestamp, error code, message and details
type ContainerError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     string                 `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerError) Reset() {
	*x = ContainerError{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerError) ProtoMessage() {}

func (x *ContainerError) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerError.ProtoReflect.Descriptor instead.
func (*ContainerError) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *ContainerError) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *ContainerError) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ContainerError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ContainerError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ContainerError) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

// ReplicaErrors is used to provide all the container errors for a replica
type ReplicaErrors struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Replica         string                 `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	ContainerErrors []*ContainerError      `protobuf:"bytes,2,rep,name=containerErrors,proto3" json:"containerErrors,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReplicaErrors) Reset() {
	*x = ReplicaErrors{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaErrors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaErrors) ProtoMessage() {}

func (x *ReplicaErrors) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaErrors.ProtoReflect.Descriptor instead.
func (*ReplicaErrors) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{16}
}

func (x *ReplicaErrors) GetReplica() string {
	if x != nil {
		return x.Replica
	}
	return ""
}

func (x *ReplicaErrors) GetContainerErrors() []*ContainerError {
	if x != nil {
		return x.ContainerErrors
	}
	return nil
}

type GetVertexErrorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errors        []*ReplicaErrors       `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVertexErrorsResponse) Reset() {
	*x = GetVertexErrorsResponse{}
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVertexErrorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVertexErrorsResponse) ProtoMessage() {}

func (x *GetVertexErrorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_proto_daemon_daemon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVertexErrorsResponse.ProtoReflect.Descriptor instead.
func (*GetVertexErrorsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP(), []int{17}
}

func (x *GetVertexErrorsResponse) GetErrors() []*ReplicaErrors {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_pkg_apis_proto_daemon_daemon_proto protoreflect.FileDescriptor

const file_pkg_apis_proto_daemon_daemon_proto_rawDesc = "" +
	"\n" +
	"\"pkg/apis/proto/daemon/daemon.proto\x12\x06daemon\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x04\n" +
	"\n" +
	"BufferInfo\x12\x1a\n" +
	"\bpipeline\x18\x01 \x01(\tR\bpipeline\x12\x1e\n" +
	"\n" +
	"bufferName\x18\x02 \x01(\tR\n" +
	"bufferName\x12?\n" +
	"\fpendingCount\x18\x03 \x01(\v2\x1b.google.protobuf.Int64ValueR\fpendingCount\x12E\n" +
	"\x0fackPendingCount\x18\x04 \x01(\v2\x1b.google.protobuf.Int64ValueR\x0fackPendingCount\x12A\n" +
	"\rtotalMessages\x18\x05 \x01(\v2\x1b.google.protobuf.Int64ValueR\rtotalMessages\x12?\n" +
	"\fbufferLength\x18\x06 \x01(\v2\x1b.google.protobuf.Int64ValueR\fbufferLength\x12H\n" +
	"\x10bufferUsageLimit\x18\a \x01(\v2\x1c.google.protobuf.DoubleValueR\x10bufferUsageLimit\x12>\n" +
	"\vbufferUsage\x18\b \x01(\v2\x1c.google.protobuf.DoubleValueR\vbufferUsage\x122\n" +
	"\x06isFull\x18\t \x01(\v2\x1a.google.protobuf.BoolValueR\x06isFull\"\x96\x03\n" +
	"\rVertexMetrics\x12\x1a\n" +
	"\bpipeline\x18\x01 \x01(\tR\bpipeline\x12\x16\n" +
	"\x06vertex\x18\x02 \x01(\tR\x06vertex\x12T\n" +
	"\x0fprocessingRates\x18\x03 \x03(\v2*.daemon.VertexMetrics.ProcessingRatesEntryR\x0fprocessingRates\x12?\n" +
	"\bpendings\x18\x04 \x03(\v2#.daemon.VertexMetrics.PendingsEntryR\bpendings\x1a`\n" +
	"\x14ProcessingRatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05value:\x028\x01\x1aX\n" +
	"\rPendingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.google.protobuf.Int64ValueR\x05value:\x028\x01\"V\n" +
	"\x0ePipelineStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"0\n" +
	"\x12ListBuffersRequest\x12\x1a\n" +
	"\bpipeline\x18\x01 \x01(\tR\bpipeline\"C\n" +
	"\x13ListBuffersResponse\x12,\n" +
	"\abuffers\x18\x01 \x03(\v2\x12.daemon.BufferInfoR\abuffers\"F\n" +
	"\x10GetBufferRequest\x12\x1a\n" +
	"\bpipeline\x18\x01 \x01(\tR\bpipeline\x12\x16\n" +
	"\x06buffer\x18\x02 \x01(\tR\x06buffer\"?\n" +
	"\x11GetBufferResponse\x12*\n" +
	"\x06buffer\x18\x01 \x01(\v2\x12.daemon.BufferInfoR\x06buffer\"6\n" +
	"\x18GetPipelineStatusRequest\x12\x1a\n" +
	"\bpipeline\x18\x01 \x01(\tR\bpipeline\"K\n" +
	"\x19GetPipelineStatusResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.daemon.PipelineStatusR\x06status\"M\n" +
	"\x17GetVertexMetricsRequest\x12\x1a\n" +
	"\bpipeline\x18\x02 \x01(\tR\bpipeline\x12\x16\n" +
	"\x06vertex\x18\x03 \x01(\tR\x06vertex\"W\n" +
	"\x18GetVertexMetricsResponse\x12;\n" +
	"\rvertexMetrics\x18\x01 \x03(\v2\x15.daemon.VertexMetricsR\rvertexMetrics\"\xec\x01\n" +
	"\rEdgeWatermark\x12\x1a\n" +
	"\bpipeline\x18\x01 \x01(\tR\bpipeline\x12\x12\n" +
	"\x04edge\x18\x02 \x01(\tR\x04edge\x12;\n" +
	"\n" +
	"watermarks\x18\x03 \x03(\v2\x1b.google.protobuf.Int64ValueR\n" +
	"watermarks\x12J\n" +
	"\x12isWatermarkEnabled\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueR\x12isWatermarkEnabled\x12\x12\n" +
	"\x04from\x18\x05 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x06 \x01(\tR\x02to\"f\n" +
	"\x1dGetPipelineWatermarksResponse\x12E\n" +
	"\x12pipelineWatermarks\x18\x01 \x03(\v2\x15.daemon.EdgeWatermarkR\x12pipelineWatermarks\":\n" +
	"\x1cGetPipelineWatermarksRequest\x12\x1a\n" +
	"\bpipeline\x18\x01 \x01(\tR\bpipeline\"L\n" +
	"\x16GetVertexErrorsRequest\x12\x1a\n" +
	"\bpipeline\x18\x01 \x01(\tR\bpipeline\x12\x16\n" +
	"\x06vertex\x18\x02 \x01(\tR\x06vertex\"\xb0\x01\n" +
	"\x0eContainerError\x12\x1c\n" +
	"\tcontainer\x18\x01 \x01(\tR\tcontainer\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x05 \x01(\tR\adetails\"k\n" +
	"\rReplicaErrors\x12\x18\n" +
	"\areplica\x18\x01 \x01(\tR\areplica\x12@\n" +
	"\x0fcontainerErrors\x18\x02 \x03(\v2\x16.daemon.ContainerErrorR\x0fcontainerErrors\"H\n" +
	"\x17GetVertexErrorsResponse\x12-\n" +
	"\x06errors\x18\x01 \x03(\v2\x15.daemon.ReplicaErrorsR\x06errors2\xca\x06\n" +
	"\rDaemonService\x12t\n" +
	"\vListBuffers\x12\x1a.daemon.ListBuffersRequest\x1a\x1b.daemon.ListBuffersResponse\",\x82\xd3\xe4\x93\x02&\x12$/api/v1/pipelines/{pipeline}/buffers\x12w\n" +
	"\tGetBuffer\x12\x18.daemon.GetBufferRequest\x1a\x19.daemon.GetBufferResponse\"5\x82\xd3\xe4\x93\x02/\x12-/api/v1/pipelines/{pipeline}/buffers/{buffer}\x12\x95\x01\n" +
	"\x10GetVertexMetrics\x12\x1f.daemon.GetVertexMetricsRequest\x1a .daemon.GetVertexMetricsResponse\">\x82\xd3\xe4\x93\x028\x126/api/v1/pipelines/{pipeline}/vertices/{vertex}/metrics\x12\x95\x01\n" +
	"\x15GetPipelineWatermarks\x12$.daemon.GetPipelineWatermarksRequest\x1a%.daemon.GetPipelineWatermarksResponse\"/\x82\xd3\xe4\x93\x02)\x12'/api/v1/pipelines/{pipeline}/watermarks\x12\x85\x01\n" +
	"\x11GetPipelineStatus\x12 .daemon.GetPipelineStatusRequest\x1a!.daemon.GetPipelineStatusResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1/pipelines/{pipeline}/status\x12\x91\x01\n" +
	"\x0fGetVertexErrors\x12\x1e.daemon.GetVertexErrorsRequest\x1a\x1f.daemon.GetVertexErrorsResponse\"=\x82\xd3\xe4\x93\x027\x125/api/v1/pipelines/{pipeline}/vertices/{vertex}/errorsB4Z2github.com/numaproj/numaflow/pkg/apis/proto/daemonb\x06proto3"

var (
	file_pkg_apis_proto_daemon_daemon_proto_rawDescOnce sync.Once
	file_pkg_apis_proto_daemon_daemon_proto_rawDescData []byte
)

func file_pkg_apis_proto_daemon_daemon_proto_rawDescGZIP() []byte {
	file_pkg_apis_proto_daemon_daemon_proto_rawDescOnce.Do(func() {
		file_pkg_apis_proto_daemon_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_apis_proto_daemon_daemon_proto_rawDesc), len(file_pkg_apis_proto_daemon_daemon_proto_rawDesc)))
	})
	return file_pkg_apis_proto_daemon_daemon_proto_rawDescData
}

var file_pkg_apis_proto_daemon_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pkg_apis_proto_daemon_daemon_proto_goTypes = []any{
	(*BufferInfo)(nil),                    // 0: daemon.BufferInfo
	(*VertexMetrics)(nil),                 // 1: daemon.VertexMetrics
	(*PipelineStatus)(nil),                // 2: daemon.PipelineStatus
	(*ListBuffersRequest)(nil),            // 3: daemon.ListBuffersRequest
	(*ListBuffersResponse)(nil),           // 4: daemon.ListBuffersResponse
	(*GetBufferRequest)(nil),              // 5: daemon.GetBufferRequest
	(*GetBufferResponse)(nil),             // 6: daemon.GetBufferResponse
	(*GetPipelineStatusRequest)(nil),      // 7: daemon.GetPipelineStatusRequest
	(*GetPipelineStatusResponse)(nil),     // 8: daemon.GetPipelineStatusResponse
	(*GetVertexMetricsRequest)(nil),       // 9: daemon.GetVertexMetricsRequest
	(*GetVertexMetricsResponse)(nil),      // 10: daemon.GetVertexMetricsResponse
	(*EdgeWatermark)(nil),                 // 11: daemon.EdgeWatermark
	(*GetPipelineWatermarksResponse)(nil), // 12: daemon.GetPipelineWatermarksResponse
	(*GetPipelineWatermarksRequest)(nil),  // 13: daemon.GetPipelineWatermarksRequest
	(*GetVertexErrorsRequest)(nil),        // 14: daemon.GetVertexErrorsRequest
	(*ContainerError)(nil),                // 15: daemon.ContainerError
	(*ReplicaErrors)(nil),                 // 16: daemon.ReplicaErrors
	(*GetVertexErrorsResponse)(nil),       // 17: daemon.GetVertexErrorsResponse
	nil,                                   // 18: daemon.VertexMetrics.ProcessingRatesEntry
	nil,                                   // 19: daemon.VertexMetrics.PendingsEntry
	(*wrapperspb.Int64Value)(nil),         // 20: google.protobuf.Int64Value
	(*wrapperspb.DoubleValue)(nil),        // 21: google.protobuf.DoubleValue
	(*wrapperspb.BoolValue)(nil),          // 22: google.protobuf.BoolValue
	(*timestamppb.Timestamp)(nil),         // 23: google.protobuf.Timestamp
}
var file_pkg_apis_proto_daemon_daemon_proto_depIdxs = []int32{
	20, // 0: daemon.BufferInfo.pendingCount:type_name -> google.protobuf.Int64Value
	20, // 1: daemon.BufferInfo.ackPendingCount:type_name -> google.protobuf.Int64Value
	20, // 2: daemon.BufferInfo.totalMessages:type_name -> google.protobuf.Int64Value
	20, // 3: daemon.BufferInfo.bufferLength:type_name -> google.protobuf.Int64Value
	21, // 4: daemon.BufferInfo.bufferUsageLimit:type_name -> google.protobuf.DoubleValue
	21, // 5: daemon.BufferInfo.bufferUsage:type_name -> google.protobuf.DoubleValue
	22, // 6: daemon.BufferInfo.isFull:type_name -> google.protobuf.BoolValue
	18, // 7: daemon.VertexMetrics.processingRates:type_name -> daemon.VertexMetrics.ProcessingRatesEntry
	19, // 8: daemon.VertexMetrics.pendings:type_name -> daemon.VertexMetrics.PendingsEntry
	0,  // 9: daemon.ListBuffersResponse.buffers:type_name -> daemon.BufferInfo
	0,  // 10: daemon.GetBufferResponse.buffer:type_name -> daemon.BufferInfo
	2,  // 11: daemon.GetPipelineStatusResponse.status:type_name -> daemon.PipelineStatus
	1,  // 12: daemon.GetVertexMetricsResponse.vertexMetrics:type_name -> daemon.VertexMetrics
	20, // 13: daemon.EdgeWatermark.watermarks:type_name -> google.protobuf.Int64Value
	22, // 14: daemon.EdgeWatermark.isWatermarkEnabled:type_name -> google.protobuf.BoolValue
	11, // 15: daemon.GetPipelineWatermarksResponse.pipelineWatermarks:type_name -> daemon.EdgeWatermark
	23, // 16: daemon.ContainerError.timestamp:type_name -> google.protobuf.Timestamp
	15, // 17: daemon.ReplicaErrors.containerErrors:type_name -> daemon.ContainerError
	16, // 18: daemon.GetVertexErrorsResponse.errors:type_name -> daemon.ReplicaErrors
	21, // 19: daemon.VertexMetrics.ProcessingRatesEntry.value:type_name -> google.protobuf.DoubleValue
	20, // 20: daemon.VertexMetrics.PendingsEntry.value:type_name -> google.protobuf.Int64Value
	3,  // 21: daemon.DaemonService.ListBuffers:input_type -> daemon.ListBuffersRequest
	5,  // 22: daemon.DaemonService.GetBuffer:input_type -> daemon.GetBufferRequest
	9,  // 23: daemon.DaemonService.GetVertexMetrics:input_type -> daemon.GetVertexMetricsRequest
	13, // 24: daemon.DaemonService.GetPipelineWatermarks:input_type -> daemon.GetPipelineWatermarksRequest
	7,  // 25: daemon.DaemonService.GetPipelineStatus:input_type -> daemon.GetPipelineStatusRequest
	14, // 26: daemon.DaemonService.GetVertexErrors:input_type -> daemon.GetVertexErrorsRequest
	4,  // 27: daemon.DaemonService.ListBuffers:output_type -> daemon.ListBuffersResponse
	6,  // 28: daemon.DaemonService.GetBuffer:output_type -> daemon.GetBufferResponse
	10, // 29: daemon.DaemonService.GetVertexMetrics:output_type -> daemon.GetVertexMetricsResponse
	12, // 30: daemon.DaemonService.GetPipelineWatermarks:output_type -> daemon.GetPipelineWatermarksResponse
	8,  // 31: daemon.DaemonService.GetPipelineStatus:output_type -> daemon.GetPipelineStatusResponse
	17, // 32: daemon.DaemonService.GetVertexErrors:output_type -> daemon.GetVertexErrorsResponse
	27, // [27:33] is the sub-list for method output_type
	21, // [21:27] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_pkg_apis_proto_daemon_daemon_proto_init() }
func file_pkg_apis_proto_daemon_daemon_proto_init() {
	if File_pkg_apis_proto_daemon_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_apis_proto_daemon_daemon_proto_rawDesc), len(file_pkg_apis_proto_daemon_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_apis_proto_daemon_daemon_proto_goTypes,
		DependencyIndexes: file_pkg_apis_proto_daemon_daemon_proto_depIdxs,
		MessageInfos:      file_pkg_apis_proto_daemon_daemon_proto_msgTypes,
	}.Build()
	File_pkg_apis_proto_daemon_daemon_proto = out.File
	file_pkg_apis_proto_daemon_daemon_proto_goTypes = nil
	file_pkg_apis_proto_daemon_daemon_proto_depIdxs = nil
}
