// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/apis/proto/daemon/daemon.proto

package daemon

import (
	context "context"
	encoding_binary "encoding/binary"
	fmt "fmt"
	github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/emptypb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// BufferInfo is used to provide information about the buffer including
// pending messages count, if it has unprocessed data etc which helps in pipeline/buffer deletion etc
type BufferInfo struct {
	Pipeline        *string `protobuf:"bytes,1,req,name=pipeline" json:"pipeline,omitempty"`
	FromVertex      *string `protobuf:"bytes,2,req,name=fromVertex" json:"fromVertex,omitempty"`
	ToVertex        *string `protobuf:"bytes,3,req,name=toVertex" json:"toVertex,omitempty"`
	BufferName      *string `protobuf:"bytes,4,req,name=bufferName" json:"bufferName,omitempty"`
	PendingCount    *int64  `protobuf:"varint,5,req,name=pendingCount" json:"pendingCount,omitempty"`
	AckPendingCount *int64  `protobuf:"varint,6,req,name=ackPendingCount" json:"ackPendingCount,omitempty"`
	// Total messages existing in the buffer, including pending, ackPending and acked.
	TotalMessages        *int64   `protobuf:"varint,7,req,name=totalMessages" json:"totalMessages,omitempty"`
	BufferLength         *int64   `protobuf:"varint,8,req,name=bufferLength" json:"bufferLength,omitempty"`
	BufferUsageLimit     *float64 `protobuf:"fixed64,9,req,name=bufferUsageLimit" json:"bufferUsageLimit,omitempty"`
	BufferUsage          *float64 `protobuf:"fixed64,10,req,name=bufferUsage" json:"bufferUsage,omitempty"`
	IsFull               *bool    `protobuf:"varint,11,req,name=isFull" json:"isFull,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BufferInfo) Reset()         { *m = BufferInfo{} }
func (m *BufferInfo) String() string { return proto.CompactTextString(m) }
func (*BufferInfo) ProtoMessage()    {}
func (*BufferInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_93e327fd0d673221, []int{0}
}
func (m *BufferInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BufferInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BufferInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BufferInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BufferInfo.Merge(m, src)
}
func (m *BufferInfo) XXX_Size() int {
	return m.Size()
}
func (m *BufferInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BufferInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BufferInfo proto.InternalMessageInfo

func (m *BufferInfo) GetPipeline() string {
	if m != nil && m.Pipeline != nil {
		return *m.Pipeline
	}
	return ""
}

func (m *BufferInfo) GetFromVertex() string {
	if m != nil && m.FromVertex != nil {
		return *m.FromVertex
	}
	return ""
}

func (m *BufferInfo) GetToVertex() string {
	if m != nil && m.ToVertex != nil {
		return *m.ToVertex
	}
	return ""
}

func (m *BufferInfo) GetBufferName() string {
	if m != nil && m.BufferName != nil {
		return *m.BufferName
	}
	return ""
}

func (m *BufferInfo) GetPendingCount() int64 {
	if m != nil && m.PendingCount != nil {
		return *m.PendingCount
	}
	return 0
}

func (m *BufferInfo) GetAckPendingCount() int64 {
	if m != nil && m.AckPendingCount != nil {
		return *m.AckPendingCount
	}
	return 0
}

func (m *BufferInfo) GetTotalMessages() int64 {
	if m != nil && m.TotalMessages != nil {
		return *m.TotalMessages
	}
	return 0
}

func (m *BufferInfo) GetBufferLength() int64 {
	if m != nil && m.BufferLength != nil {
		return *m.BufferLength
	}
	return 0
}

func (m *BufferInfo) GetBufferUsageLimit() float64 {
	if m != nil && m.BufferUsageLimit != nil {
		return *m.BufferUsageLimit
	}
	return 0
}

func (m *BufferInfo) GetBufferUsage() float64 {
	if m != nil && m.BufferUsage != nil {
		return *m.BufferUsage
	}
	return 0
}

func (m *BufferInfo) GetIsFull() bool {
	if m != nil && m.IsFull != nil {
		return *m.IsFull
	}
	return false
}

type VertexInfo struct {
	Pipeline             *string  `protobuf:"bytes,1,req,name=pipeline" json:"pipeline,omitempty"`
	Vertex               *string  `protobuf:"bytes,2,req,name=vertex" json:"vertex,omitempty"`
	Rate                 *int64   `protobuf:"varint,3,req,name=rate" json:"rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VertexInfo) Reset()         { *m = VertexInfo{} }
func (m *VertexInfo) String() string { return proto.CompactTextString(m) }
func (*VertexInfo) ProtoMessage()    {}
func (*VertexInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_93e327fd0d673221, []int{1}
}
func (m *VertexInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VertexInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VertexInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VertexInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VertexInfo.Merge(m, src)
}
func (m *VertexInfo) XXX_Size() int {
	return m.Size()
}
func (m *VertexInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VertexInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VertexInfo proto.InternalMessageInfo

func (m *VertexInfo) GetPipeline() string {
	if m != nil && m.Pipeline != nil {
		return *m.Pipeline
	}
	return ""
}

func (m *VertexInfo) GetVertex() string {
	if m != nil && m.Vertex != nil {
		return *m.Vertex
	}
	return ""
}

func (m *VertexInfo) GetRate() int64 {
	if m != nil && m.Rate != nil {
		return *m.Rate
	}
	return 0
}

type ListBuffersRequest struct {
	Pipeline             *string  `protobuf:"bytes,1,req,name=pipeline" json:"pipeline,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBuffersRequest) Reset()         { *m = ListBuffersRequest{} }
func (m *ListBuffersRequest) String() string { return proto.CompactTextString(m) }
func (*ListBuffersRequest) ProtoMessage()    {}
func (*ListBuffersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_93e327fd0d673221, []int{2}
}
func (m *ListBuffersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListBuffersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListBuffersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListBuffersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBuffersRequest.Merge(m, src)
}
func (m *ListBuffersRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListBuffersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBuffersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBuffersRequest proto.InternalMessageInfo

func (m *ListBuffersRequest) GetPipeline() string {
	if m != nil && m.Pipeline != nil {
		return *m.Pipeline
	}
	return ""
}

type ListBuffersResponse struct {
	Buffers              []*BufferInfo `protobuf:"bytes,1,rep,name=buffers" json:"buffers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListBuffersResponse) Reset()         { *m = ListBuffersResponse{} }
func (m *ListBuffersResponse) String() string { return proto.CompactTextString(m) }
func (*ListBuffersResponse) ProtoMessage()    {}
func (*ListBuffersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93e327fd0d673221, []int{3}
}
func (m *ListBuffersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListBuffersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListBuffersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListBuffersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBuffersResponse.Merge(m, src)
}
func (m *ListBuffersResponse) XXX_Size() int {
	return m.Size()
}
func (m *ListBuffersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBuffersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBuffersResponse proto.InternalMessageInfo

func (m *ListBuffersResponse) GetBuffers() []*BufferInfo {
	if m != nil {
		return m.Buffers
	}
	return nil
}

type GetBufferRequest struct {
	Pipeline             *string  `protobuf:"bytes,1,req,name=pipeline" json:"pipeline,omitempty"`
	Buffer               *string  `protobuf:"bytes,2,req,name=buffer" json:"buffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBufferRequest) Reset()         { *m = GetBufferRequest{} }
func (m *GetBufferRequest) String() string { return proto.CompactTextString(m) }
func (*GetBufferRequest) ProtoMessage()    {}
func (*GetBufferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_93e327fd0d673221, []int{4}
}
func (m *GetBufferRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetBufferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetBufferRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetBufferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBufferRequest.Merge(m, src)
}
func (m *GetBufferRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetBufferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBufferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBufferRequest proto.InternalMessageInfo

func (m *GetBufferRequest) GetPipeline() string {
	if m != nil && m.Pipeline != nil {
		return *m.Pipeline
	}
	return ""
}

func (m *GetBufferRequest) GetBuffer() string {
	if m != nil && m.Buffer != nil {
		return *m.Buffer
	}
	return ""
}

type GetBufferResponse struct {
	Buffer               *BufferInfo `protobuf:"bytes,1,req,name=buffer" json:"buffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetBufferResponse) Reset()         { *m = GetBufferResponse{} }
func (m *GetBufferResponse) String() string { return proto.CompactTextString(m) }
func (*GetBufferResponse) ProtoMessage()    {}
func (*GetBufferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93e327fd0d673221, []int{5}
}
func (m *GetBufferResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetBufferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetBufferResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetBufferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBufferResponse.Merge(m, src)
}
func (m *GetBufferResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetBufferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBufferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBufferResponse proto.InternalMessageInfo

func (m *GetBufferResponse) GetBuffer() *BufferInfo {
	if m != nil {
		return m.Buffer
	}
	return nil
}

type GetVertexRequest struct {
	Pipeline             *string  `protobuf:"bytes,1,req,name=pipeline" json:"pipeline,omitempty"`
	Vertex               *string  `protobuf:"bytes,2,req,name=vertex" json:"vertex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVertexRequest) Reset()         { *m = GetVertexRequest{} }
func (m *GetVertexRequest) String() string { return proto.CompactTextString(m) }
func (*GetVertexRequest) ProtoMessage()    {}
func (*GetVertexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_93e327fd0d673221, []int{6}
}
func (m *GetVertexRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetVertexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetVertexRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetVertexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVertexRequest.Merge(m, src)
}
func (m *GetVertexRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetVertexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVertexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVertexRequest proto.InternalMessageInfo

func (m *GetVertexRequest) GetPipeline() string {
	if m != nil && m.Pipeline != nil {
		return *m.Pipeline
	}
	return ""
}

func (m *GetVertexRequest) GetVertex() string {
	if m != nil && m.Vertex != nil {
		return *m.Vertex
	}
	return ""
}

type GetVertexResponse struct {
	Vertex               *VertexInfo `protobuf:"bytes,1,req,name=vertex" json:"vertex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetVertexResponse) Reset()         { *m = GetVertexResponse{} }
func (m *GetVertexResponse) String() string { return proto.CompactTextString(m) }
func (*GetVertexResponse) ProtoMessage()    {}
func (*GetVertexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93e327fd0d673221, []int{7}
}
func (m *GetVertexResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetVertexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetVertexResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetVertexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVertexResponse.Merge(m, src)
}
func (m *GetVertexResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetVertexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVertexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVertexResponse proto.InternalMessageInfo

func (m *GetVertexResponse) GetVertex() *VertexInfo {
	if m != nil {
		return m.Vertex
	}
	return nil
}

func init() {
	proto.RegisterType((*BufferInfo)(nil), "daemon.BufferInfo")
	proto.RegisterType((*VertexInfo)(nil), "daemon.VertexInfo")
	proto.RegisterType((*ListBuffersRequest)(nil), "daemon.ListBuffersRequest")
	proto.RegisterType((*ListBuffersResponse)(nil), "daemon.ListBuffersResponse")
	proto.RegisterType((*GetBufferRequest)(nil), "daemon.GetBufferRequest")
	proto.RegisterType((*GetBufferResponse)(nil), "daemon.GetBufferResponse")
	proto.RegisterType((*GetVertexRequest)(nil), "daemon.GetVertexRequest")
	proto.RegisterType((*GetVertexResponse)(nil), "daemon.GetVertexResponse")
}

func init() {
	proto.RegisterFile("pkg/apis/proto/daemon/daemon.proto", fileDescriptor_93e327fd0d673221)
}

var fileDescriptor_93e327fd0d673221 = []byte{
	// 592 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x95, 0x9d, 0x7e, 0x69, 0x7b, 0xf3, 0x55, 0x94, 0x41, 0xaa, 0x8c, 0x8b, 0x22, 0xcb, 0xaa,
	0x90, 0x55, 0x95, 0x0c, 0x44, 0xb0, 0x06, 0xb5, 0xa8, 0x08, 0x29, 0x20, 0x64, 0x7e, 0x16, 0xec,
	0x9c, 0x74, 0xec, 0x9a, 0xda, 0x33, 0xc6, 0x33, 0x4e, 0x41, 0x51, 0x36, 0x7d, 0x05, 0x5e, 0x8a,
	0x25, 0x12, 0x2f, 0x80, 0x22, 0x9e, 0x81, 0x35, 0xf2, 0xcc, 0x38, 0xb1, 0xd3, 0xa8, 0x64, 0xe5,
	0xb9, 0xe7, 0xfe, 0x9c, 0x33, 0xe7, 0xda, 0x06, 0x37, 0xbb, 0x88, 0x70, 0x90, 0xc5, 0x1c, 0x67,
	0x39, 0x13, 0x0c, 0x9f, 0x05, 0x24, 0x65, 0x54, 0x3f, 0x7a, 0x12, 0x43, 0x6d, 0x15, 0xd9, 0xf7,
	0x22, 0xc6, 0xa2, 0x84, 0x94, 0xe5, 0x38, 0xa0, 0x94, 0x89, 0x40, 0xc4, 0x8c, 0x72, 0x55, 0x65,
	0xef, 0xeb, 0xac, 0x8c, 0x86, 0x45, 0x88, 0x49, 0x9a, 0x89, 0xaf, 0x2a, 0xe9, 0x5e, 0xb5, 0x00,
	0x8e, 0x8b, 0x30, 0x24, 0xf9, 0x4b, 0x1a, 0x32, 0x64, 0xc3, 0x56, 0x16, 0x67, 0x24, 0x89, 0x29,
	0xb1, 0x0c, 0xc7, 0xf4, 0xb6, 0xfd, 0x79, 0x8c, 0xba, 0x00, 0x61, 0xce, 0xd2, 0x0f, 0x24, 0x17,
	0xe4, 0x8b, 0x65, 0xca, 0x6c, 0x0d, 0x29, 0x7b, 0x05, 0xd3, 0xd9, 0x96, 0xea, 0xad, 0xe2, 0xb2,
	0x77, 0x28, 0x59, 0x5e, 0x07, 0x29, 0xb1, 0x36, 0x54, 0xef, 0x02, 0x41, 0x2e, 0xfc, 0x9f, 0x11,
	0x7a, 0x16, 0xd3, 0xe8, 0x84, 0x15, 0x54, 0x58, 0xff, 0x39, 0xa6, 0xd7, 0xf2, 0x1b, 0x18, 0xf2,
	0xe0, 0x56, 0x30, 0xba, 0x78, 0x53, 0x2f, 0x6b, 0xcb, 0xb2, 0x65, 0x18, 0x1d, 0xc0, 0x8e, 0x60,
	0x22, 0x48, 0x5e, 0x11, 0xce, 0x83, 0x88, 0x70, 0x6b, 0x53, 0xd6, 0x35, 0xc1, 0x92, 0x53, 0x29,
	0x18, 0x10, 0x1a, 0x89, 0x73, 0x6b, 0x4b, 0x71, 0xd6, 0x31, 0x74, 0x08, 0xbb, 0x2a, 0x7e, 0x5f,
	0xf6, 0x0c, 0xe2, 0x34, 0x16, 0xd6, 0xb6, 0x63, 0x7a, 0x86, 0x7f, 0x0d, 0x47, 0x0e, 0x74, 0x6a,
	0x98, 0x05, 0xb2, 0xac, 0x0e, 0xa1, 0x3d, 0x68, 0xc7, 0xfc, 0xb4, 0x48, 0x12, 0xab, 0xe3, 0x98,
	0xde, 0x96, 0xaf, 0x23, 0xf7, 0x1d, 0x80, 0xf2, 0xe9, 0x9f, 0x3b, 0xd8, 0x83, 0xf6, 0xb8, 0xee,
	0xbf, 0x8e, 0x10, 0x82, 0x8d, 0x3c, 0x10, 0x44, 0xfa, 0xde, 0xf2, 0xe5, 0xd9, 0x7d, 0x08, 0x68,
	0x10, 0x73, 0xa1, 0xb6, 0xcb, 0x7d, 0xf2, 0xb9, 0x20, 0x5c, 0xdc, 0x34, 0xdd, 0x3d, 0x81, 0x3b,
	0x8d, 0x0e, 0x9e, 0x31, 0xca, 0x09, 0x3a, 0x82, 0x4d, 0x75, 0x0b, 0x6e, 0x19, 0x4e, 0xcb, 0xeb,
	0xf4, 0x51, 0x4f, 0xbf, 0x86, 0x8b, 0x37, 0xc7, 0xaf, 0x4a, 0xdc, 0x53, 0xd8, 0x7d, 0x41, 0xf4,
	0x8c, 0x35, 0x48, 0xcb, 0x2b, 0xa9, 0xd6, 0xea, 0x4a, 0x2a, 0x72, 0x9f, 0xc2, 0xed, 0xda, 0x1c,
	0x2d, 0xe5, 0x70, 0x5e, 0x5c, 0x8e, 0x59, 0xad, 0xa4, 0x1a, 0xa0, 0x84, 0x28, 0x63, 0xd7, 0x14,
	0xb2, 0xca, 0x5b, 0x2d, 0xa4, 0x9a, 0xb3, 0x10, 0xa2, 0x8b, 0x97, 0x84, 0x2c, 0x16, 0x59, 0x0d,
	0xe8, 0xff, 0x31, 0x61, 0xe7, 0xb9, 0xcc, 0xbe, 0x25, 0xf9, 0x38, 0x1e, 0x11, 0x24, 0xa0, 0x53,
	0x33, 0x1a, 0xd9, 0x55, 0xf3, 0xf5, 0x7d, 0xd9, 0xfb, 0x2b, 0x73, 0x4a, 0x85, 0x7b, 0x74, 0xf5,
	0xf3, 0xf7, 0x37, 0xf3, 0x3e, 0x3a, 0x90, 0x9f, 0xfe, 0xf8, 0x11, 0xae, 0x2e, 0xc3, 0xf1, 0xa4,
	0x3a, 0x4e, 0xb1, 0xde, 0x0c, 0xba, 0x84, 0xed, 0xb9, 0xa3, 0xc8, 0xaa, 0xe6, 0x2e, 0x2f, 0xcb,
	0xbe, 0xbb, 0x22, 0xa3, 0xf9, 0x9e, 0x48, 0x3e, 0x8c, 0x1e, 0xac, 0xc3, 0x87, 0x27, 0xea, 0x30,
	0x45, 0x63, 0x49, 0xac, 0x7f, 0x05, 0x75, 0xe2, 0xc6, 0x72, 0x1a, 0xc4, 0x4d, 0xbb, 0xdd, 0xc7,
	0x92, 0xb8, 0x87, 0x8e, 0x6e, 0x24, 0x56, 0x7e, 0xe3, 0x89, 0x7a, 0x4e, 0x8f, 0x9f, 0x7d, 0x9f,
	0x75, 0x8d, 0x1f, 0xb3, 0xae, 0xf1, 0x6b, 0xd6, 0x35, 0x3e, 0xf6, 0xa3, 0x58, 0x9c, 0x17, 0xc3,
	0xde, 0x88, 0xa5, 0x98, 0x16, 0x69, 0x90, 0xe5, 0xec, 0x93, 0x3c, 0x84, 0x09, 0xbb, 0xc4, 0x2b,
	0x7f, 0xb7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x94, 0x74, 0x03, 0x5e, 0x86, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DaemonServiceClient interface {
	ListBuffers(ctx context.Context, in *ListBuffersRequest, opts ...grpc.CallOption) (*ListBuffersResponse, error)
	GetBuffer(ctx context.Context, in *GetBufferRequest, opts ...grpc.CallOption) (*GetBufferResponse, error)
	GetVertex(ctx context.Context, in *GetVertexRequest, opts ...grpc.CallOption) (*GetVertexResponse, error)
}

type daemonServiceClient struct {
	cc *grpc.ClientConn
}

func NewDaemonServiceClient(cc *grpc.ClientConn) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) ListBuffers(ctx context.Context, in *ListBuffersRequest, opts ...grpc.CallOption) (*ListBuffersResponse, error) {
	out := new(ListBuffersResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/ListBuffers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetBuffer(ctx context.Context, in *GetBufferRequest, opts ...grpc.CallOption) (*GetBufferResponse, error) {
	out := new(GetBufferResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/GetBuffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetVertex(ctx context.Context, in *GetVertexRequest, opts ...grpc.CallOption) (*GetVertexResponse, error) {
	out := new(GetVertexResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/GetVertex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServiceServer is the server API for DaemonService service.
type DaemonServiceServer interface {
	ListBuffers(context.Context, *ListBuffersRequest) (*ListBuffersResponse, error)
	GetBuffer(context.Context, *GetBufferRequest) (*GetBufferResponse, error)
	GetVertex(context.Context, *GetVertexRequest) (*GetVertexResponse, error)
}

// UnimplementedDaemonServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDaemonServiceServer struct {
}

func (*UnimplementedDaemonServiceServer) ListBuffers(ctx context.Context, req *ListBuffersRequest) (*ListBuffersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBuffers not implemented")
}
func (*UnimplementedDaemonServiceServer) GetBuffer(ctx context.Context, req *GetBufferRequest) (*GetBufferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBuffer not implemented")
}
func (*UnimplementedDaemonServiceServer) GetVertex(ctx context.Context, req *GetVertexRequest) (*GetVertexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVertex not implemented")
}

func RegisterDaemonServiceServer(s *grpc.Server, srv DaemonServiceServer) {
	s.RegisterService(&_DaemonService_serviceDesc, srv)
}

func _DaemonService_ListBuffers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBuffersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListBuffers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/ListBuffers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListBuffers(ctx, req.(*ListBuffersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetBuffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBufferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetBuffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/GetBuffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetBuffer(ctx, req.(*GetBufferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetVertex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVertexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetVertex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/GetVertex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetVertex(ctx, req.(*GetVertexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DaemonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "daemon.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBuffers",
			Handler:    _DaemonService_ListBuffers_Handler,
		},
		{
			MethodName: "GetBuffer",
			Handler:    _DaemonService_GetBuffer_Handler,
		},
		{
			MethodName: "GetVertex",
			Handler:    _DaemonService_GetVertex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apis/proto/daemon/daemon.proto",
}

func (m *BufferInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BufferInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BufferInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.IsFull == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("isFull")
	} else {
		i--
		if *m.IsFull {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if m.BufferUsage == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("bufferUsage")
	} else {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(*m.BufferUsage))))
		i--
		dAtA[i] = 0x51
	}
	if m.BufferUsageLimit == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("bufferUsageLimit")
	} else {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(*m.BufferUsageLimit))))
		i--
		dAtA[i] = 0x49
	}
	if m.BufferLength == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("bufferLength")
	} else {
		i = encodeVarintDaemon(dAtA, i, uint64(*m.BufferLength))
		i--
		dAtA[i] = 0x40
	}
	if m.TotalMessages == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("totalMessages")
	} else {
		i = encodeVarintDaemon(dAtA, i, uint64(*m.TotalMessages))
		i--
		dAtA[i] = 0x38
	}
	if m.AckPendingCount == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("ackPendingCount")
	} else {
		i = encodeVarintDaemon(dAtA, i, uint64(*m.AckPendingCount))
		i--
		dAtA[i] = 0x30
	}
	if m.PendingCount == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("pendingCount")
	} else {
		i = encodeVarintDaemon(dAtA, i, uint64(*m.PendingCount))
		i--
		dAtA[i] = 0x28
	}
	if m.BufferName == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("bufferName")
	} else {
		i -= len(*m.BufferName)
		copy(dAtA[i:], *m.BufferName)
		i = encodeVarintDaemon(dAtA, i, uint64(len(*m.BufferName)))
		i--
		dAtA[i] = 0x22
	}
	if m.ToVertex == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("toVertex")
	} else {
		i -= len(*m.ToVertex)
		copy(dAtA[i:], *m.ToVertex)
		i = encodeVarintDaemon(dAtA, i, uint64(len(*m.ToVertex)))
		i--
		dAtA[i] = 0x1a
	}
	if m.FromVertex == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("fromVertex")
	} else {
		i -= len(*m.FromVertex)
		copy(dAtA[i:], *m.FromVertex)
		i = encodeVarintDaemon(dAtA, i, uint64(len(*m.FromVertex)))
		i--
		dAtA[i] = 0x12
	}
	if m.Pipeline == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("pipeline")
	} else {
		i -= len(*m.Pipeline)
		copy(dAtA[i:], *m.Pipeline)
		i = encodeVarintDaemon(dAtA, i, uint64(len(*m.Pipeline)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VertexInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VertexInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VertexInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Rate == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("rate")
	} else {
		i = encodeVarintDaemon(dAtA, i, uint64(*m.Rate))
		i--
		dAtA[i] = 0x18
	}
	if m.Vertex == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("vertex")
	} else {
		i -= len(*m.Vertex)
		copy(dAtA[i:], *m.Vertex)
		i = encodeVarintDaemon(dAtA, i, uint64(len(*m.Vertex)))
		i--
		dAtA[i] = 0x12
	}
	if m.Pipeline == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("pipeline")
	} else {
		i -= len(*m.Pipeline)
		copy(dAtA[i:], *m.Pipeline)
		i = encodeVarintDaemon(dAtA, i, uint64(len(*m.Pipeline)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ListBuffersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListBuffersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListBuffersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Pipeline == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("pipeline")
	} else {
		i -= len(*m.Pipeline)
		copy(dAtA[i:], *m.Pipeline)
		i = encodeVarintDaemon(dAtA, i, uint64(len(*m.Pipeline)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ListBuffersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListBuffersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListBuffersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Buffers) > 0 {
		for iNdEx := len(m.Buffers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Buffers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDaemon(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GetBufferRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetBufferRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetBufferRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Buffer == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("buffer")
	} else {
		i -= len(*m.Buffer)
		copy(dAtA[i:], *m.Buffer)
		i = encodeVarintDaemon(dAtA, i, uint64(len(*m.Buffer)))
		i--
		dAtA[i] = 0x12
	}
	if m.Pipeline == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("pipeline")
	} else {
		i -= len(*m.Pipeline)
		copy(dAtA[i:], *m.Pipeline)
		i = encodeVarintDaemon(dAtA, i, uint64(len(*m.Pipeline)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetBufferResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetBufferResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetBufferResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Buffer == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("buffer")
	} else {
		{
			size, err := m.Buffer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDaemon(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetVertexRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetVertexRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetVertexRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Vertex == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("vertex")
	} else {
		i -= len(*m.Vertex)
		copy(dAtA[i:], *m.Vertex)
		i = encodeVarintDaemon(dAtA, i, uint64(len(*m.Vertex)))
		i--
		dAtA[i] = 0x12
	}
	if m.Pipeline == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("pipeline")
	} else {
		i -= len(*m.Pipeline)
		copy(dAtA[i:], *m.Pipeline)
		i = encodeVarintDaemon(dAtA, i, uint64(len(*m.Pipeline)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetVertexResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetVertexResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetVertexResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Vertex == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("vertex")
	} else {
		{
			size, err := m.Vertex.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDaemon(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDaemon(dAtA []byte, offset int, v uint64) int {
	offset -= sovDaemon(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BufferInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pipeline != nil {
		l = len(*m.Pipeline)
		n += 1 + l + sovDaemon(uint64(l))
	}
	if m.FromVertex != nil {
		l = len(*m.FromVertex)
		n += 1 + l + sovDaemon(uint64(l))
	}
	if m.ToVertex != nil {
		l = len(*m.ToVertex)
		n += 1 + l + sovDaemon(uint64(l))
	}
	if m.BufferName != nil {
		l = len(*m.BufferName)
		n += 1 + l + sovDaemon(uint64(l))
	}
	if m.PendingCount != nil {
		n += 1 + sovDaemon(uint64(*m.PendingCount))
	}
	if m.AckPendingCount != nil {
		n += 1 + sovDaemon(uint64(*m.AckPendingCount))
	}
	if m.TotalMessages != nil {
		n += 1 + sovDaemon(uint64(*m.TotalMessages))
	}
	if m.BufferLength != nil {
		n += 1 + sovDaemon(uint64(*m.BufferLength))
	}
	if m.BufferUsageLimit != nil {
		n += 9
	}
	if m.BufferUsage != nil {
		n += 9
	}
	if m.IsFull != nil {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *VertexInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pipeline != nil {
		l = len(*m.Pipeline)
		n += 1 + l + sovDaemon(uint64(l))
	}
	if m.Vertex != nil {
		l = len(*m.Vertex)
		n += 1 + l + sovDaemon(uint64(l))
	}
	if m.Rate != nil {
		n += 1 + sovDaemon(uint64(*m.Rate))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ListBuffersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pipeline != nil {
		l = len(*m.Pipeline)
		n += 1 + l + sovDaemon(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ListBuffersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Buffers) > 0 {
		for _, e := range m.Buffers {
			l = e.Size()
			n += 1 + l + sovDaemon(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetBufferRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pipeline != nil {
		l = len(*m.Pipeline)
		n += 1 + l + sovDaemon(uint64(l))
	}
	if m.Buffer != nil {
		l = len(*m.Buffer)
		n += 1 + l + sovDaemon(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetBufferResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Buffer != nil {
		l = m.Buffer.Size()
		n += 1 + l + sovDaemon(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetVertexRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pipeline != nil {
		l = len(*m.Pipeline)
		n += 1 + l + sovDaemon(uint64(l))
	}
	if m.Vertex != nil {
		l = len(*m.Vertex)
		n += 1 + l + sovDaemon(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetVertexResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Vertex != nil {
		l = m.Vertex.Size()
		n += 1 + l + sovDaemon(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovDaemon(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDaemon(x uint64) (n int) {
	return sovDaemon(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BufferInfo) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDaemon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BufferInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BufferInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pipeline", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDaemon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDaemon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Pipeline = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromVertex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDaemon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDaemon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.FromVertex = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToVertex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDaemon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDaemon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ToVertex = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BufferName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDaemon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDaemon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.BufferName = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000008)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingCount", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PendingCount = &v
			hasFields[0] |= uint64(0x00000010)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AckPendingCount", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AckPendingCount = &v
			hasFields[0] |= uint64(0x00000020)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalMessages", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TotalMessages = &v
			hasFields[0] |= uint64(0x00000040)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BufferLength", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BufferLength = &v
			hasFields[0] |= uint64(0x00000080)
		case 9:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field BufferUsageLimit", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			v2 := float64(math.Float64frombits(v))
			m.BufferUsageLimit = &v2
			hasFields[0] |= uint64(0x00000100)
		case 10:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field BufferUsage", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			v2 := float64(math.Float64frombits(v))
			m.BufferUsage = &v2
			hasFields[0] |= uint64(0x00000200)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsFull", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.IsFull = &b
			hasFields[0] |= uint64(0x00000400)
		default:
			iNdEx = preIndex
			skippy, err := skipDaemon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDaemon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("pipeline")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("fromVertex")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("toVertex")
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("bufferName")
	}
	if hasFields[0]&uint64(0x00000010) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("pendingCount")
	}
	if hasFields[0]&uint64(0x00000020) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("ackPendingCount")
	}
	if hasFields[0]&uint64(0x00000040) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("totalMessages")
	}
	if hasFields[0]&uint64(0x00000080) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("bufferLength")
	}
	if hasFields[0]&uint64(0x00000100) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("bufferUsageLimit")
	}
	if hasFields[0]&uint64(0x00000200) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("bufferUsage")
	}
	if hasFields[0]&uint64(0x00000400) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("isFull")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VertexInfo) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDaemon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VertexInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VertexInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pipeline", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDaemon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDaemon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Pipeline = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vertex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDaemon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDaemon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Vertex = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rate", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Rate = &v
			hasFields[0] |= uint64(0x00000004)
		default:
			iNdEx = preIndex
			skippy, err := skipDaemon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDaemon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("pipeline")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("vertex")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("rate")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListBuffersRequest) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDaemon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListBuffersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListBuffersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pipeline", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDaemon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDaemon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Pipeline = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipDaemon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDaemon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("pipeline")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListBuffersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDaemon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListBuffersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListBuffersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buffers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDaemon
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDaemon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Buffers = append(m.Buffers, &BufferInfo{})
			if err := m.Buffers[len(m.Buffers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDaemon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDaemon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetBufferRequest) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDaemon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetBufferRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetBufferRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pipeline", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDaemon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDaemon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Pipeline = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buffer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDaemon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDaemon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Buffer = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipDaemon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDaemon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("pipeline")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("buffer")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetBufferResponse) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDaemon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetBufferResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetBufferResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buffer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDaemon
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDaemon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Buffer == nil {
				m.Buffer = &BufferInfo{}
			}
			if err := m.Buffer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipDaemon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDaemon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("buffer")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetVertexRequest) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDaemon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetVertexRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetVertexRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pipeline", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDaemon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDaemon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Pipeline = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vertex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDaemon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDaemon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Vertex = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipDaemon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDaemon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("pipeline")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("vertex")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetVertexResponse) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDaemon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetVertexResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetVertexResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vertex", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDaemon
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDaemon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Vertex == nil {
				m.Vertex = &VertexInfo{}
			}
			if err := m.Vertex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipDaemon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDaemon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("vertex")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDaemon(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDaemon
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDaemon
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDaemon
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDaemon
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDaemon
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDaemon        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDaemon          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDaemon = fmt.Errorf("proto: unexpected end of group")
)
