// This file is @generated by prost-build.
/// SegmentHeader for the Aligned Wall.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SegmentHeader {
    /// start_time of the window
    #[prost(message, optional, tag = "1")]
    pub start_time: ::core::option::Option<::prost_types::Timestamp>,
    /// end_time = start_time + window
    #[prost(message, optional, tag = "2")]
    pub end_time: ::core::option::Option<::prost_types::Timestamp>,
    /// this is currently set to 0 (in the future we can split large windows to multiple slots)
    #[prost(string, tag = "3")]
    pub slot: ::prost::alloc::string::String,
}
