apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  vertices:
    - name: in
      scale:
        min: 1
      # A self data generating source
      source:
        generator:
          rpu: 5
          duration: 1s
        transformer:
          container:
            image: quay.io/numaio/numaflow-rs/source-transformer-now:stable
    - name: cat
      scale:
        min: 1
      udf:
        container:
          # Tell the input number is even or odd, see https://github.com/numaproj/numaflow-go/tree/main/pkg/mapper/examples/even_odd
          image: quay.io/numaio/numaflow-rs/map-cat:stable
    - name: out
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: cat
    - from: cat
      to: out