apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  vertices:
    - name: in
      scale:
        min: 1
      source:
        # A self data generating source
        http: {}
    - name: cat
      scale:
        min: 1
      udf:
        builtin:
          name: cat # A built-in UDF which simply cats the message
    - name: out
      scale:
        min: 1
      sink:
        # A simple log printing sink
        log: {}
  edges:
    - from: in
      to: cat
    - from: cat
      to: out