apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  vertices:
    - name: in
      scale:
        min: 1
      # A self data generating source
      source:
        generator:
          rpu: 100
          duration: 1s
    - name: cat
      containerTemplate:
        env:
          - name: NUMAFLOW_RUNTIME
            value: "rust"
      partitions: 3
      scale:
        min: 2
        max: 2
      udf:
        container:
          image: quay.io/numaio/numaflow-go/map-flatmap:stable
          imagePullPolicy: Never
    - name: out
#      containerTemplate:
#        env:
#          - name: NUMAFLOW_RUNTIME
#            value: "rust"
      scale:
        min: 2
        max: 2
      sink:
        udsink:
          container:
            image: quay.io/numaio/numaflow-go/sink-log:stable
            imagePullPolicy: Never
  edges:
    - from: in
      to: cat
    - from: cat
      to: out
