apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  interStepBufferServiceName: custom
  limits:
    bufferMaxLength: 150000
    bufferUsageLimit: 85
    readBatchSize: 1000
  vertices:
    - name: in
      containerTemplate:
        securityContext:
          capabilities:
            add:
              - “SYS_PTRACE”
        env:
          - name: NUMAFLOW_PIPELINE_STREAMING
            value: "true"
          - name: PAF_BATCH_SIZE
            value: "1000"
      source:
        generator:
          rpu: 10000
          duration: 1s
    - name: out
      partitions: 3
      scale:
        min: 1
      sink:
        blackhole: {}
  edges:
    - from: in
      to: out