# FIXME(cr): revert the changes
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  watermark:
    disabled: true
  limits:
    readBatchSize: 1000
  vertices:
    - name: in
      scale:
        min: 1
      source:
        generator:
          rpu: 100000
          msgSize: 300
          duration: 1s

    - name: out
      partitions: 5
      scale:
        min: 5
      sink:
        blackhole: {}
  edges:
    - from: in
      to: out
