# This pipeline uses gzip compression for ISB
# Available out of the box only in Rust based backend, i.e, 1.6
# In 1.5, you can switch to Rust backend by setting NUMAFLOW_RUNTIME environment variable to "rust"

apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  interStepBuffer:
      compression:
        type: gzip
  vertices:
    - name: in
      scale:
        min: 1
      # A self data generating source
      source:
        generator:
          rpu: 5
          duration: 1s
    - name: cat
      scale:
        min: 1
      udf:
        container:
          image: quay.io/numaio/numaflow-go/map-forward-message:stable
    - name: out
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: cat
    - from: cat
      to: out
