apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  vertices:
    - name: in-one
      scale:
        min: 1
      # A self data generating source
      source:
        generator:
          rpu: 5
          duration: 1s
    - name: in-two
      scale:
        min: 1
      # A self data generating source
      source:
        generator:
          rpu: 5
          duration: 1s
    - name: cat
      partitions: 3
      scale:
        min: 1
      udf:
        container:
          image: quay.io/numaio/numaflow-go/map-cat:stable # A UDF which simply cats the message
          imagePullPolicy: Always
    - name: out
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in-one
      to: cat
    - from: in-two
      to: cat
    - from: cat
      to: out