apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  limits:
    readBatchSize: 1000
  vertices:
    - name: in
      scale:
        min: 1
      # A self data generating source
      source:
        generator:
          rpu: 100
          msgSize: 100
          duration: 1s

    - name: out
      scale:
        min: 1
      sink:
        blackhole: {}
  edges:
    - from: in
      to: out
