apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  vertices:
    - name: in
      scale:
        min: 1
      # A self data generating source
      source:
        generator:
          rpu: 5
          duration: 1s
    - name: cat-one
      scale:
        min: 1
      udf:
        builtin:
          name: cat # A builtin UDF which simply cats the message
    - name: cat-two
      scale:
        min: 1
      udf:
        builtin:
          name: cat # A builtin UDF which simply cats the message
    - name: cat-three
      scale:
        min: 1
      udf:
        builtin:
          name: cat # A builtin UDF which simply cats the message
    - name: out
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: cat-one
    - from: cat-one
      to: cat-two
    - from: cat-two
      to: cat-three
    - from: cat-three
      to: out