apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  vertices:
    - name: input
      source:
        # A self data generating source
        generator:
          rpu: 5
          duration: 1s
    - name: cat
      udf:
        builtin:
          name: cat # A builtin UDF which simply cats the message
    - name: output
      sink:
        # A simple log printing sink
        log: {}
  edges:
    - from: input
      to: cat
    - from: cat
      to: output
