apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  vertices:
    - name: in
      source:
        # A self data generating source
        generator:
          rpu: 5
          duration: 1s
    - name: cat
      containerTemplate:
        env:
          - name: NUMAFLOW_DEBUG
            value: "true"
      scale:
        min: 1 # Minimum replicas
      udf:
        builtin:
          name: cat # A built-in UDF which simply cats the message
    - name: out
      containerTemplate:
        env:
          - name: NUMAFLOW_DEBUG
            value: "true"
      scale:
        min: 1 # Minimum replicas
      sink:
        # A simple log printing sink
        log: {}
  edges:
    - from: in
      to: cat
    - from: cat
      to: out
