apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  watermark:
    disabled: true
  limits:
    bufferMaxLength: 150000
    bufferUsageLimit: 85
  vertices:
    - name: in
      scale:
        min: 1
      containerTemplate:
        env:
          - name: NUMAFLOW_PIPELINE_STREAMING
            value: "true"
          - name: PAF_BATCH_SIZE
            value: "1000"
      source:
        generator:
          rpu: 50000
          msgSize: 40
          duration: 1s
    - name: out
      scale:
        min: 1
      sink:
        blackhole: {}
  edges:
    - from: in
      to: out