apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  vertices:
    - name: in
      scale:
        min: 1
      # A self data generating source
      source:
        generator:
          rpu: 3000
          duration: 1s
    - name: cat
      containerTemplate:
        env:
          - name: NUMAFLOW_RUNTIME
            value: "rust"
      scale:
        min: 1
        max: 1
      udf:
        container:
          image: quay.io/numaio/numaflow-go/map-flatmap-stream:stable
          imagePullPolicy: Never
    - name: out
#      containerTemplate:
#        env:
#          - name: NUMAFLOW_RUNTIME
#            value: "rust"
      scale:
        min: 1
        max: 1
      sink:
        log: {}
  edges:
    - from: in
      to: cat
    - from: cat
      to: out
