apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  watermark:
    disabled: true
  vertices:
    - name: in
      scale:
        min: 1
      # A self data generating source
      source:
        udsource:
          container:
            image: quay.io/numaio/numaflow-go/source-simple-source:stable
            imagePullPolicy: Never
    - name: cat
      partitions: 2
      scale:
        min: 1
        max: 1
      udf:
        container:
          image: quay.io/numaio/numaflow-go/map-forward-message:stable
          imagePullPolicy: Never
    - name: out
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: cat
    - from: cat
      to: out