apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: join-on-map
spec:
  vertices:
    - name: http-one
      scale:
        min: 1
      source:
        http: {}
    - name: http-two
      scale:
        min: 1
      source:
        http: {}
    # Both of the incoming Vertices join on this Map Vertex
    - name: cat
      scale:
        min: 1
      udf:
        container:
          image: quay.io/numaio/numaflow-go/map-stream-sorter:stable
          imagePullPolicy: Never
    - name: out
      scale:
        min: 1
      sink:
        # A simple log printing sink
        log: {}
  edges:
    - from: http-one
      to: cat
    - from: http-two
      to: cat
    - from: cat
      to: out
