apiVersion: v1
kind: Secret
metadata:
  name: gssapi
data:
  username: a2Fma2F0ZXN0L2hvc3QubGltYS5pbnRlcm5hbAo=
  password: cm9vdAo=
  config: |
    W2xpYmRlZmF1bHRzXQogIGRlZmF1bHRfcmVhbG0gPSBFWEFNUExFLkNPTQogIHVkcF9wcmVmZXJl
    bmNlX2xpbWl0ID0gMQoKW3JlYWxtc10KICBFWEFNUExFLkNPTSA9IHsKICAgIGtkYyA9IGhvc3Qu
    bGltYS5pbnRlcm5hbDo4OAogICAgYWRtaW5fc2VydmVyID0gaG9zdC5saW1hLmludGVybmFsOjc0
    OQogIH0KCltkb21haW5fcmVhbG1dCiAgLmV4YW1wbGUuY29tID0gRVhBTVBMRS5DT00KICBleGFt
    cGxlLmNvbSA9IEVYQU1QTEUuQ09NCg==

---
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: join-on-map
spec:
  vertices:
    - name: kafka-in
      scale:
        min: 1
        max: 1
      containerTemplate:
        env:
          - name: NUMAFLOW_RUNTIME
            value: "rust"
      source:
        kafka:
          brokers:
            - host.lima.internal:9094
          topic: my-topic
          consumerGroup: my-consumer-group
          sasl:
            mechanism: GSSAPI
            gssapi:
              serviceName: kafka
              realm: EXAMPLE.COM
              authType: KRB5_USER_AUTH
              usernameSecret: # Pointing to a secret reference which contains the username
                name: gssapi
                key: username
              passwordSecret: # Pointing to a secret reference which contains the username
                name: gssapi
                key: password
              kerberosConfigSecret: # Pointing to a secret reference which contains the kerberos config
                name: gssapi
                key: config

    - name: out
      scale:
        min: 1
        max: 1
      containerTemplate:
        env:
          - name: NUMAFLOW_RUNTIME
            value: "rust"
      sink:
        # A simple log printing sink
        log: {}
  edges:
    - from: kafka-in
      to: out
