apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-session-counter
spec:
  vertices:
    - name: in
      containerTemplate:
        env:
          - name: NUMAFLOW_RUNTIME
            value: "rust"
      scale:
        min: 1
      source:
        http: {}
    - name: even-odd
      containerTemplate:
        env:
          - name: NUMAFLOW_RUNTIME
            value: "rust"
      scale:
        min: 1
      udf:
        container:
          image: quay.io/numaio/numaflow-go/map-forward-message:stable
    - name: compute-count
      containerTemplate:
        env:
          - name: NUMAFLOW_RUNTIME
            value: "rust"
      partitions: 1
      udf:
        container:
          # see https://github.com/numaproj/numaflow-go/tree/main/pkg/sessionreducer/examples/counter
          # computes the count of even numbers and odd numbers in a session
          image: quay.io/numaio/numaflow-rs/session-counter:stable
          imagePullPolicy: Never
        groupBy:
          window:
            session:
              timeout: 10s # session window will be closed after 120 seconds of inactivity
          keyed: true
          storage:
            persistentVolumeClaim:
              volumeSize: 2Gi
              accessMode: ReadWriteOnce
    - name: sink
      containerTemplate:
        env:
          - name: NUMAFLOW_RUNTIME
            value: "rust"
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: even-odd
    - from: even-odd
      to: compute-count
    - from: compute-count
      to: sink
