apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-streaming-reduce
spec:
  watermark:
    maxDelay: 30s
  vertices:
    - name: in
      source:
        http: {}
    - name: atoi
      scale:
        min: 1
      udf:
        container:
          # Tell the input number is even or odd, see https://github.com/numaproj/numaflow-go/tree/main/examples/mapper/even_odd
          image: quay.io/numaio/numaflow-go/map-even-odd:stable
          imagePullPolicy: Always
    - name: compute-sum
      partitions: 2
      udf:
        container:
          # compute the sum, see https://github.com/numaproj/numaflow-go/tree/main/examples/reducestreamer/sum
          # Writes output to next vertex if the sum is greater than 100, does not wait for the window to close.
          image: quay.io/numaio/numaflow-go/reduce-stream-sum:stable
          imagePullPolicy: Always
        groupBy:
          window:
            fixed:
              length: 600s
              streaming: true # set streaming to true to enable reduce streamer
          keyed: true
          storage:
            persistentVolumeClaim:
              volumeSize: 1Gi
              accessMode: ReadWriteOncePod
    - name: sink
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: atoi
    - from: atoi
      to: compute-sum
    - from: compute-sum
      to: sink
