apiVersion: numaflow.numaproj.io/v1alpha1
kind: MonoVertex
metadata:
  name: simple-mono-vertex-builtin
spec:
  source:
    # A self data generating (built-in) source.
    generator:
      rpu: 5
      duration: 1s
  sink:
    # A built-in log sink that prints the messages it receives.
    log: {}
