apiVersion: numaflow.numaproj.io/v1alpha1
kind: MonoVertex
metadata:
  name: simple-mono-vertex
spec:
  source:
    udsource:
      container:
        image: quay.io/numaio/numaflow-rs/simple-source:stable
        imagePullPolicy: Always

  sink:
    udsink:
      container:
        image: quay.io/numaio/numaflow-rs/blackhole-sink:stable
        imagePullPolicy: Always