apiVersion: numaflow.numaproj.io/v1alpha1
kind: MonoVertex
metadata:
  name: simple-mono-vertex
spec:
  source:
    udsource:
      container:
        image: quay.io/numaio/numaflow-rs/simple-source:stable
    # transformer is an optional container to do any transformation
    transformer:
      container:
        image: quay.io/numaio/numaflow-rs/source-transformer-now:stable
  # map is an optional container to do any map operations (available from Numaflow Version 1.7)
  udf:
    container:
      image: quay.io/numaio/numaflow-go/map-cat:stable
      imagePullPolicy: IfNotPresent        
  sink:
    udsink:
      container:
        image: quay.io/numaio/numaflow-rs/sink-log:stable
    # fallback is an optional container for sink to fallback to incase the primary sink has failures
    fallback:
      udsink:
        container:
          image: quay.io/numaio/numaflow-go/fb-sink-log:stable
