apiVersion: numaflow.numaproj.io/v1alpha1
kind: MonoVertex
metadata:
  name: oms-sink-mono-vertex
  annotations:
    kubectl.kubernetes.io/default-container: numa
  labels:
    app.kubernetes.io/component: mono-vertex
    app.kubernetes.io/part-of: numaflow
    env: e2e
    assetId: "2024385625830654788"
    namespace: oss-analytics-numaflowendurancestable-usw2-e2e
    assetAlias: Intuit.oss.analytics.numaflowendurancestable
    region: us-west-2
spec:
  source:
    generator:
      rpu: 1
      duration: 1s
      keyCount: 1000
  sink:
    udsink:
      container:
        args:
          - --spring.config.location=file:/conf/oms-config.yaml
          - --numaflow.handler=oms-sink
        image: docker.intuit.com/personal/vtiwari5/oms-numaflow:0.0.4
        imagePullPolicy: Always
        env:
          - name: LOGGING_LEVEL_COM_INTUIT_OSSANALYTICS_NUMAFLOW
            value: 'DEBUG'
          - name: MANAGEMENT_SERVER_PORT
            value: "8499"
          - name: SERVER_PORT
            value: "8089"
        volumeMounts:
          - mountPath: /conf
            name: oms-config-volume
  containerTemplate:
    resources: { }
  scale:
    max: 1
    min: 1
  volumes:
    - configMap:
        items:
          - key: configuration
            path: oms-config.yaml
        name: oms-config
      name: oms-config-volume
