apiVersion: numaflow.numaproj.io/v1alpha1
kind: ServingPipeline
metadata:
  name: serving-pipeline
spec:
  serving:
    metadata:
      annotations:
        key1: val1
      labels:
        key2: val2
    service: true
    msgIDHeaderKey: "X-Numaflow-Id"
  pipeline:
    limits:
      readTimeout: 20ms
    vertices:
      - name: in
        scale:
          min: 1
        source:
          serving: {}
      - name: cat
        scale:
          min: 1
        udf:
          container:
            image: quay.io/numaio/numaflow-go/map-forward-message:stable
      - name: out
        scale:
          min: 1
        sink:
          serve: {}
    edges:
      - from: in
        to: cat
      - from: cat
        to: out
