apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  servingStore:
    name: ips
    container:
      image: quay.io/numaio/numaflow-go/serving-redis-store:stable
      imagePullPolicy: Never

  vertices:
    - name: serving-in
      servingStoreName: ""
      scale:
        min: 1
      source:
        serving:
          service: true
          msgIDHeaderKey: "X-Numaflow-Id"

    - name: cat
      scale:
        min: 1
      udf:
        container:
          image: quay.io/numaio/numaflow-go/map-flatmap-stream:stable
          imagePullPolicy: Never
          env:
            - name: RUST_BACKTRACE
              value: "1"
            - name: SLEEP_SECONDS
              value: "30"

    - name: serve-sink
      servingStoreName: default
      scale:
        min: 1
      sink:
        udsink:
          container:
            image: quay.io/numaio/numaflow-go/sink-serve:stable
            imagePullPolicy: Never
            env:
              - name: NUMAFLOW_CALLBACK_URL_KEY
                value: "X-Numaflow-Callback-Url"
              - name: NUMAFLOW_MSG_ID_HEADER_KEY
                value: "X-Numaflow-Id"

  edges:
    - from: serving-in
      to: cat
    - from: cat
      to: serve-sink

