apiVersion: numaflow.numaproj.io/v1alpha1
kind: ServingPipeline
metadata:
  name: serving-pipeline
spec:
  serving:
    service: true
    msgIDHeaderKey: "X-Numaflow-Id"
  pipeline:
    vertices:
      - name: in
        source:
          serving: {}
      - name: cat
        udf:
          container:
            image: quay.io/numaio/numaflow-go/map-forward-message:stable
      - name: out
        sink:
          serve: {}
    edges:
      - from: in
        to: cat
      - from: cat
        to: out
