apiVersion: numaflow.numaproj.io/v1alpha1
kind: ServingPipeline
metadata:
  name: serving-pipeline
spec:
  serving:
    service: true
    msgIDHeaderKey: "X-Numaflow-Id"
    store:
      container:
        image: quay.io/numaio/numaflow-go/serving-redis-store:stable

  pipeline:
    vertices:
      - name: serving-in
        scale:
          min: 1
        source:
          serving: {}

      - name: cat
        scale:
          min: 1
        udf:
          container:
            image: quay.io/numaio/numaflow-go/map-forward-message:stable

      - name: serve-sink
        scale:
          min: 1
        sink:
          serve: {}

    edges:
      - from: serving-in
        to: cat
      - from: cat
        to: serve-sink



