apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  servingStore:
    name: ips
    container:
      image: <container-image>
      imagePullPolicy: Always
  vertices:
    - name: serving-in
      servingStoreName: ips
      scale:
        min: 1
      source:
        serving:
          service: true
          msgIDHeaderKey: "X-Numaflow-Id"
          store:
            container:
              image: docker.intuit.com/quay-rmt/numaio/redis:v1.5.0-alpha1
              env:
                - name: ENV
                  value: "QAL"

    - name: cat
      scale:
        min: 1
      udf:
        container:
          image: quay.io/numaio/numaflow-go/map-forward-message:stable
          env:
            - name: RUST_BACKTRACE
              value: "1"

    - name: serve-sink
      servingStoreName: ips
      scale:
        min: 1
      sink:
        udsink:
          container:
            image: docker.intuit.com/quay-rmt/numaio/servesink:v1.5.0-alpha1
            env:
              - name: NUMAFLOW_CALLBACK_URL_KEY
                value: "X-Numaflow-Callback-Url"
              - name: NUMAFLOW_MSG_ID_HEADER_KEY
                value: "X-Numaflow-Id"

  edges:
    - from: serving-in
      to: cat
    - from: cat
      to: serve-sink