apiVersion: numaflow.numaproj.io/v1alpha1
kind: ServingPipeline
metadata:
  name: serving-sse-pipeline
spec:
  serving:
    service: true
    msgIDHeaderKey: "X-Numaflow-Id"
  pipeline:
    vertices:
      - name: serving-in
        servingStoreName: default
        scale:
          min: 1
        source:
          serving: {}

      - name: cat
        scale:
          min: 1
        udf:
          container:
            image: quay.io/numaio/numaflow-go/map-flatmap-stream:latest

      - name: serve-sink
        servingStoreName: default
        scale:
          min: 1
        sink:
          udsink:
            container:
              image: quay.io/numaio/numaflow-go/sink-serve:stable

    edges:
      - from: serving-in
        to: cat
      - from: cat
        to: serve-sink