apiVersion: numaflow.numaproj.io/v1alpha1
kind: ServingPipeline
metadata:
  name: ascii-art-pipeline
spec:
  serving:
    service: true
    msgIDHeaderKey: "X-Numaflow-Id"
  pipeline:
    limits:
      readTimeout: 20ms
    vertices:
      - name: in
        containerTemplate:
          imagePullPolicy: IfNotPresent
        scale:
          min: 1
        source:
          serving: {}

      - name: planner
        scale:
          min: 1
        udf:
          container:
            image: docker.intuit.com/personal/srao12/numavllm/planner:v1

      - name: inference
        nodeSelector:
          node.kubernetes.io/instancegroup: nodes-gpu
        tolerations:
          - key: ig/nodesgpu
            operator: "Exists"
        scale:
          min: 1
        udf:
          container:
            image: docker.intuit.com/personal/srao12/numavllm/numavllmimg-diffuse:v3
            env:
              - name: HUGGING_FACE_HUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: hf-token-secret
                    key: hf_api_token
              - name: MODEL_TYPE
                value: "infer"
            resources:
              limits:
                cpu: "7"
                memory: 20G
                nvidia.com/gpu: "1"
              requests:
                cpu: "2"
                memory: 12G
                nvidia.com/gpu: "1"

      - name: diffusion
        nodeSelector:
          node.kubernetes.io/instancegroup: nodes-gpu
        tolerations:
          - key: ig/nodesgpu
            operator: "Exists"
        scale:
          min: 1
        udf:
          container:
            image: docker.intuit.com/personal/srao12/numavllm/numavllmimg-diffuse:v3
            env:
              - name: HUGGING_FACE_HUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: hf-token-secret
                    key: hf_api_token
              - name: MODEL_TYPE
                value: "diffuse"
            resources:
              limits:
                cpu: "7"
                memory: 20G
                nvidia.com/gpu: "1"
              requests:
                cpu: "2"
                memory: 12G
                nvidia.com/gpu: "1"

      - name: serve-sink
        scale:
          min: 1
        sink:
          serve: {}

      - name: error-sink
        scale:
          min: 1
        sink:
          serve: {}
    edges:
      - from: in
        to: planner
      - from: planner
        to: inference
        conditions:
          tags:
            operator: or
            values:
              - infer
      - from: planner
        to: diffusion
        conditions:
          tags:
            operator: or
            values:
              - diffuse
      - from: inference
        to: serve-sink
      - from: diffusion
        to: serve-sink
      - from: planner
        to: error-sink
        conditions:
          tags:
            operator: or
            values:
              - error
      - from: inference
        to: error-sink
        conditions:
          tags:
            operator: or
            values:
              - error
      - from: diffusion
        to: error-sink
        conditions:
          tags:
            operator: or
            values:
              - error
