apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: udsink-pipeline
spec:
  vertices:
    - name: in
      source:
        generator:
          rpu: 1
          duration: 1s
          msgSize: 10
    - name: p1
      udf:
        container:
          image: quay.io/numaio/numaflow-go/map-cat:stable # A UDF which simply cats the message
          imagePullPolicy: Always
    - name: out
      sink:
        udsink:
          container:
            image: my-sink:latest
  edges:
    - from: in
      to: p1
    - from: p1
      to: out
