apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: autoscaling-pipeline
spec:
  vertices:
    - name: in
      source:
        # A self data generating source
        generator:
          rpu: 50
          duration: 1s
    - name: cat
      scale:
        min: 2 # Minimum replicas
        max: 4 # Maximum replicas
      udf:
        container:
          image: quay.io/numaio/numaflow-go/map-cat:stable # A UDF which simply cats the message
          imagePullPolicy: Always
    - name: out
      scale:
        min: 3 # Minimum replicas
        max: 5 # Maximum replicas
      sink:
        # A simple log printing sink
        log: {}
  edges:
    - from: in
      to: cat
    - from: cat
      to: out
