apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-accumulator
spec:
  vertices:
    - name: in
      source:
        generator:
          rpu: 1
          keyCount: 1
    - name: accum
      udf:
        container:
          # compute the sum
          image: quay.io/numaio/numaflow-go/simple-accumulator:stable
          imagePullPolicy: Never
        groupBy:
          window:
            accumulator:
              ttl: 10s
          keyed: true
          storage:
            emptyDir: {}
    - name: sink
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: accum
    - from: accum
      to: sink
