apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: even-odd-sum
spec:
  vertices:
    - name: in
      containerTemplate:
        env:
          - name: NUMAFLOW_RUNTIME
            value: "rust"
      source:
        generator:
          rpu: 1
          keyCount: 1
    - name: compute-count
      containerTemplate:
        env:
          - name: NUMAFLOW_RUNTIME
            value: "rust"
      udf:
        container:
          # compute the sum
          image: quay.io/numaio/numaflow-go/reduce-counter:stable
        groupBy:
          window:
            fixed:
              length: 5s
          keyed: true
          storage:
            emptyDir: {}
    - name: sink
      containerTemplate:
        env:
          - name: NUMAFLOW_RUNTIME
            value: "rust"
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: compute-count
    - from: compute-count
      to: sink