apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: numaflow-role-binding
  labels:
    app.kubernetes.io/name: numaflow-controller-manager
    app.kubernetes.io/part-of: numaflow
    app.kubernetes.io/component: controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: numaflow-role
subjects:
  - kind: ServiceAccount
    name: numaflow-sa
