apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: numaflow-role
  labels:
    app.kubernetes.io/name: numaflow-controller-manager
    app.kubernetes.io/part-of: numaflow
    app.kubernetes.io/component: controller-manager
rules:
  - apiGroups:
      - numaflow.numaproj.io
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    resources:
      - interstepbufferservices
      - interstepbufferservices/finalizers
      - interstepbufferservices/status
      - pipelines
      - pipelines/finalizers
      - pipelines/status
      - vertices
      - vertices/finalizers
      - vertices/status
      - vertices/scale
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - configmaps
      - services
      - persistentvolumeclaims
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
