apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: numaflow-server-role
rules:
  - apiGroups:
      - numaflow.numaproj.io
    verbs:
      - get
      - list
      - watch
    resources:
      - interstepbufferservices
      - interstepbufferservices/finalizers
      - interstepbufferservices/status
      - pipelines
      - pipelines/finalizers
      - pipelines/status
      - vertices
      - vertices/finalizers
      - vertices/status
      - vertices/scale
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - pods/log
      - configmaps
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
