/*
Copyright 2022 The Numaproj Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/numaproj/numaflow/pkg/apis/numaflow/v1alpha1"
	scheme "github.com/numaproj/numaflow/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// InterStepBufferServicesGetter has a method to return a InterStepBufferServiceInterface.
// A group's client should implement this interface.
type InterStepBufferServicesGetter interface {
	InterStepBufferServices(namespace string) InterStepBufferServiceInterface
}

// InterStepBufferServiceInterface has methods to work with InterStepBufferService resources.
type InterStepBufferServiceInterface interface {
	Create(ctx context.Context, interStepBufferService *v1alpha1.InterStepBufferService, opts v1.CreateOptions) (*v1alpha1.InterStepBufferService, error)
	Update(ctx context.Context, interStepBufferService *v1alpha1.InterStepBufferService, opts v1.UpdateOptions) (*v1alpha1.InterStepBufferService, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, interStepBufferService *v1alpha1.InterStepBufferService, opts v1.UpdateOptions) (*v1alpha1.InterStepBufferService, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.InterStepBufferService, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.InterStepBufferServiceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InterStepBufferService, err error)
	InterStepBufferServiceExpansion
}

// interStepBufferServices implements InterStepBufferServiceInterface
type interStepBufferServices struct {
	*gentype.ClientWithList[*v1alpha1.InterStepBufferService, *v1alpha1.InterStepBufferServiceList]
}

// newInterStepBufferServices returns a InterStepBufferServices
func newInterStepBufferServices(c *NumaflowV1alpha1Client, namespace string) *interStepBufferServices {
	return &interStepBufferServices{
		gentype.NewClientWithList[*v1alpha1.InterStepBufferService, *v1alpha1.InterStepBufferServiceList](
			"interstepbufferservices",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.InterStepBufferService { return &v1alpha1.InterStepBufferService{} },
			func() *v1alpha1.InterStepBufferServiceList { return &v1alpha1.InterStepBufferServiceList{} }),
	}
}
