/*
Copyright 2022 The Numaproj Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/numaproj/numaflow/pkg/apis/numaflow/v1alpha1"
	scheme "github.com/numaproj/numaflow/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VerticesGetter has a method to return a VertexInterface.
// A group's client should implement this interface.
type VerticesGetter interface {
	Vertices(namespace string) VertexInterface
}

// VertexInterface has methods to work with Vertex resources.
type VertexInterface interface {
	Create(ctx context.Context, vertex *v1alpha1.Vertex, opts v1.CreateOptions) (*v1alpha1.Vertex, error)
	Update(ctx context.Context, vertex *v1alpha1.Vertex, opts v1.UpdateOptions) (*v1alpha1.Vertex, error)
	UpdateStatus(ctx context.Context, vertex *v1alpha1.Vertex, opts v1.UpdateOptions) (*v1alpha1.Vertex, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Vertex, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VertexList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Vertex, err error)
	VertexExpansion
}

// vertices implements VertexInterface
type vertices struct {
	client rest.Interface
	ns     string
}

// newVertices returns a Vertices
func newVertices(c *NumaflowV1alpha1Client, namespace string) *vertices {
	return &vertices{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vertex, and returns the corresponding vertex object, and an error if there is any.
func (c *vertices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Vertex, err error) {
	result = &v1alpha1.Vertex{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vertices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Vertices that match those selectors.
func (c *vertices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VertexList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VertexList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vertices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vertices.
func (c *vertices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vertices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a vertex and creates it.  Returns the server's representation of the vertex, and an error, if there is any.
func (c *vertices) Create(ctx context.Context, vertex *v1alpha1.Vertex, opts v1.CreateOptions) (result *v1alpha1.Vertex, err error) {
	result = &v1alpha1.Vertex{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vertices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vertex).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a vertex and updates it. Returns the server's representation of the vertex, and an error, if there is any.
func (c *vertices) Update(ctx context.Context, vertex *v1alpha1.Vertex, opts v1.UpdateOptions) (result *v1alpha1.Vertex, err error) {
	result = &v1alpha1.Vertex{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vertices").
		Name(vertex.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vertex).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *vertices) UpdateStatus(ctx context.Context, vertex *v1alpha1.Vertex, opts v1.UpdateOptions) (result *v1alpha1.Vertex, err error) {
	result = &v1alpha1.Vertex{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vertices").
		Name(vertex.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vertex).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the vertex and deletes it. Returns an error if one occurs.
func (c *vertices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vertices").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vertices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vertices").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched vertex.
func (c *vertices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Vertex, err error) {
	result = &v1alpha1.Vertex{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vertices").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
