apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: numaflow-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: numaflow-role
subjects:
  - kind: ServiceAccount
    name: numaflow-sa
