/*
 * Numaflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Authorization {
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<crate::models::V1PeriodSecretKeySelector>,
}

impl Authorization {
    pub fn new() -> Authorization {
        Authorization {
            token: None,
        }
    }
}


