/*
 * Numaflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BasicAuth : BasicAuth represents the basic authentication approach which contains a user name and a password.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BasicAuth {
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<models::V1PeriodSecretKeySelector>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<models::V1PeriodSecretKeySelector>,
}

impl BasicAuth {
    /// BasicAuth represents the basic authentication approach which contains a user name and a password.
    pub fn new() -> BasicAuth {
        BasicAuth {
            password: None,
            user: None,
        }
    }
}

