/*
 * Numaflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FixedWindow : FixedWindow describes a fixed window



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FixedWindow {
    #[serde(rename = "length", skip_serializing_if = "Option::is_none")]
    pub length: Option<k8s_openapi::apimachinery::pkg::apis::meta::v1::Duration>,
    /// Streaming should be set to true if the reduce udf is streaming.
    #[serde(rename = "streaming", skip_serializing_if = "Option::is_none")]
    pub streaming: Option<bool>,
}

impl FixedWindow {
    /// FixedWindow describes a fixed window
    pub fn new() -> FixedWindow {
        FixedWindow {
            length: None,
            streaming: None,
        }
    }
}


