/*
 * Numaflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContainerReq {
    #[serde(rename = "env")]
    pub env: Vec<crate::models::V1PeriodEnvVar>,
    #[serde(rename = "image")]
    pub image: String,
    #[serde(rename = "imagePullPolicy")]
    pub image_pull_policy: String,
    #[serde(rename = "isbSvcType")]
    pub isb_svc_type: String,
    #[serde(rename = "resources")]
    pub resources: crate::models::V1PeriodResourceRequirements,
    #[serde(rename = "volumeMounts")]
    pub volume_mounts: Vec<crate::models::V1PeriodVolumeMount>,
}

impl GetContainerReq {
    pub fn new(env: Vec<crate::models::V1PeriodEnvVar>, image: String, image_pull_policy: String, isb_svc_type: String, resources: crate::models::V1PeriodResourceRequirements, volume_mounts: Vec<crate::models::V1PeriodVolumeMount>) -> GetContainerReq {
        GetContainerReq {
            env,
            image,
            image_pull_policy,
            isb_svc_type,
            resources,
            volume_mounts,
        }
    }
}


