/*
 * Numaflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetJetStreamStatefulSetSpecReq {
    #[serde(rename = "ClientPort")]
    pub client_port: i32,
    #[serde(rename = "ClusterPort")]
    pub cluster_port: i32,
    #[serde(rename = "ConfigMapName")]
    pub config_map_name: String,
    #[serde(rename = "ConfigReloaderImage")]
    pub config_reloader_image: String,
    #[serde(rename = "DefaultResources")]
    pub default_resources: crate::models::V1PeriodResourceRequirements,
    #[serde(rename = "Labels")]
    pub labels: ::std::collections::HashMap<String, String>,
    #[serde(rename = "MetricsExporterImage")]
    pub metrics_exporter_image: String,
    #[serde(rename = "MetricsPort")]
    pub metrics_port: i32,
    #[serde(rename = "MonitorPort")]
    pub monitor_port: i32,
    #[serde(rename = "NatsImage")]
    pub nats_image: String,
    #[serde(rename = "PvcNameIfNeeded")]
    pub pvc_name_if_needed: String,
    #[serde(rename = "ServerAuthSecretName")]
    pub server_auth_secret_name: String,
    #[serde(rename = "ServerEncryptionSecretName")]
    pub server_encryption_secret_name: String,
    #[serde(rename = "ServiceName")]
    pub service_name: String,
    #[serde(rename = "StartCommand")]
    pub start_command: String,
}

impl GetJetStreamStatefulSetSpecReq {
    pub fn new(client_port: i32, cluster_port: i32, config_map_name: String, config_reloader_image: String, default_resources: crate::models::V1PeriodResourceRequirements, labels: ::std::collections::HashMap<String, String>, metrics_exporter_image: String, metrics_port: i32, monitor_port: i32, nats_image: String, pvc_name_if_needed: String, server_auth_secret_name: String, server_encryption_secret_name: String, service_name: String, start_command: String) -> GetJetStreamStatefulSetSpecReq {
        GetJetStreamStatefulSetSpecReq {
            client_port,
            cluster_port,
            config_map_name,
            config_reloader_image,
            default_resources,
            labels,
            metrics_exporter_image,
            metrics_port,
            monitor_port,
            nats_image,
            pvc_name_if_needed,
            server_auth_secret_name,
            server_encryption_secret_name,
            service_name,
            start_command,
        }
    }
}


