/*
 * Numaflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GroupBy : GroupBy indicates it is a reducer UDF



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupBy {
    #[serde(rename = "allowedLateness", skip_serializing_if = "Option::is_none")]
    pub allowed_lateness: Option<k8s_openapi::apimachinery::pkg::apis::meta::v1::Duration>,
    #[serde(rename = "keyed", skip_serializing_if = "Option::is_none")]
    pub keyed: Option<bool>,
    #[serde(rename = "storage", skip_serializing_if = "Option::is_none")]
    pub storage: Option<Box<crate::models::PbqStorage>>,
    #[serde(rename = "window")]
    pub window: Box<crate::models::Window>,
}

impl GroupBy {
    /// GroupBy indicates it is a reducer UDF
    pub fn new(window: crate::models::Window) -> GroupBy {
        GroupBy {
            allowed_lateness: None,
            keyed: None,
            storage: None,
            window: Box::new(window),
        }
    }
}


