/*
 * Numaflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NatsAuth : NatsAuth defines how to authenticate the nats access



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NatsAuth {
    #[serde(rename = "basic", skip_serializing_if = "Option::is_none")]
    pub basic: Option<Box<crate::models::BasicAuth>>,
    #[serde(rename = "nkey", skip_serializing_if = "Option::is_none")]
    pub nkey: Option<crate::models::V1PeriodSecretKeySelector>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<crate::models::V1PeriodSecretKeySelector>,
}

impl NatsAuth {
    /// NatsAuth defines how to authenticate the nats access
    pub fn new() -> NatsAuth {
        NatsAuth {
            basic: None,
            nkey: None,
            token: None,
        }
    }
}


