/*
 * Numaflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SaslPlain {
    #[serde(rename = "handshake")]
    pub handshake: bool,
    #[serde(rename = "passwordSecret", skip_serializing_if = "Option::is_none")]
    pub password_secret: Option<crate::models::V1PeriodSecretKeySelector>,
    #[serde(rename = "userSecret")]
    pub user_secret: crate::models::V1PeriodSecretKeySelector,
}

impl SaslPlain {
    pub fn new(handshake: bool, user_secret: crate::models::V1PeriodSecretKeySelector) -> SaslPlain {
        SaslPlain {
            handshake,
            password_secret: None,
            user_secret,
        }
    }
}


