/*
 * Numaflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SlidingWindow : SlidingWindow describes a sliding window



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SlidingWindow {
    #[serde(rename = "length", skip_serializing_if = "Option::is_none")]
    pub length: Option<k8s_openapi::apimachinery::pkg::apis::meta::v1::Duration>,
    #[serde(rename = "slide", skip_serializing_if = "Option::is_none")]
    pub slide: Option<k8s_openapi::apimachinery::pkg::apis::meta::v1::Duration>,
    /// Streaming should be set to true if the reduce udf is streaming.
    #[serde(rename = "streaming", skip_serializing_if = "Option::is_none")]
    pub streaming: Option<bool>,
}

impl SlidingWindow {
    /// SlidingWindow describes a sliding window
    pub fn new() -> SlidingWindow {
        SlidingWindow {
            length: None,
            slide: None,
            streaming: None,
        }
    }
}


