/*
Copyright 2022 The Numaproj Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/numaproj/numaflow/pkg/apis/numaflow/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// InterStepBufferServiceLister helps list InterStepBufferServices.
// All objects returned here must be treated as read-only.
type InterStepBufferServiceLister interface {
	// List lists all InterStepBufferServices in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.InterStepBufferService, err error)
	// InterStepBufferServices returns an object that can list and get InterStepBufferServices.
	InterStepBufferServices(namespace string) InterStepBufferServiceNamespaceLister
	InterStepBufferServiceListerExpansion
}

// interStepBufferServiceLister implements the InterStepBufferServiceLister interface.
type interStepBufferServiceLister struct {
	listers.ResourceIndexer[*v1alpha1.InterStepBufferService]
}

// NewInterStepBufferServiceLister returns a new InterStepBufferServiceLister.
func NewInterStepBufferServiceLister(indexer cache.Indexer) InterStepBufferServiceLister {
	return &interStepBufferServiceLister{listers.New[*v1alpha1.InterStepBufferService](indexer, v1alpha1.Resource("interstepbufferservice"))}
}

// InterStepBufferServices returns an object that can list and get InterStepBufferServices.
func (s *interStepBufferServiceLister) InterStepBufferServices(namespace string) InterStepBufferServiceNamespaceLister {
	return interStepBufferServiceNamespaceLister{listers.NewNamespaced[*v1alpha1.InterStepBufferService](s.ResourceIndexer, namespace)}
}

// InterStepBufferServiceNamespaceLister helps list and get InterStepBufferServices.
// All objects returned here must be treated as read-only.
type InterStepBufferServiceNamespaceLister interface {
	// List lists all InterStepBufferServices in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.InterStepBufferService, err error)
	// Get retrieves the InterStepBufferService from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.InterStepBufferService, error)
	InterStepBufferServiceNamespaceListerExpansion
}

// interStepBufferServiceNamespaceLister implements the InterStepBufferServiceNamespaceLister
// interface.
type interStepBufferServiceNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.InterStepBufferService]
}
