/*
 * Numaflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

/// ContainerTemplate : ContainerTemplate defines customized spec for a container

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerTemplate {
    #[serde(rename = "env", skip_serializing_if = "Option::is_none")]
    pub env: Option<Vec<k8s_openapi::api::core::v1::EnvVar>>,
    #[serde(rename = "envFrom", skip_serializing_if = "Option::is_none")]
    pub env_from: Option<Vec<k8s_openapi::api::core::v1::EnvFromSource>>,
    #[serde(rename = "imagePullPolicy", skip_serializing_if = "Option::is_none")]
    pub image_pull_policy: Option<String>,
    #[serde(rename = "resources", skip_serializing_if = "Option::is_none")]
    pub resources: Option<k8s_openapi::api::core::v1::ResourceRequirements>,
    #[serde(rename = "securityContext", skip_serializing_if = "Option::is_none")]
    pub security_context: Option<k8s_openapi::api::core::v1::SecurityContext>,
}

impl ContainerTemplate {
    /// ContainerTemplate defines customized spec for a container
    pub fn new() -> ContainerTemplate {
        ContainerTemplate {
            env: None,
            env_from: None,
            image_pull_policy: None,
            resources: None,
            security_context: None,
        }
    }
}
