/*
 * Numaflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Edge {
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Box<crate::models::ForwardConditions>>,
    #[serde(rename = "from")]
    pub from: String,
    /// OnFull specifies the behaviour for the write actions when the inter step buffer is full. There are currently two options, retryUntilSuccess and discardLatest. if not provided, the default value is set to \"retryUntilSuccess\"
    #[serde(rename = "onFull", skip_serializing_if = "Option::is_none")]
    pub on_full: Option<String>,
    #[serde(rename = "to")]
    pub to: String,
}

impl Edge {
    pub fn new(from: String, to: String) -> Edge {
        Edge {
            conditions: None,
            from,
            on_full: None,
            to,
        }
    }
}
