/*
 * Numaflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMonoVertexDaemonDeploymentReq {
    #[serde(rename = "DefaultResources")]
    pub default_resources: k8s_openapi::api::core::v1::ResourceRequirements,
    #[serde(rename = "Env")]
    pub env: Vec<k8s_openapi::api::core::v1::EnvVar>,
    #[serde(rename = "Image")]
    pub image: String,
    #[serde(rename = "PullPolicy")]
    pub pull_policy: String,
}

impl GetMonoVertexDaemonDeploymentReq {
    pub fn new(
        default_resources: k8s_openapi::api::core::v1::ResourceRequirements,
        env: Vec<k8s_openapi::api::core::v1::EnvVar>,
        image: String,
        pull_policy: String,
    ) -> GetMonoVertexDaemonDeploymentReq {
        GetMonoVertexDaemonDeploymentReq {
            default_resources,
            env,
            image,
            pull_policy,
        }
    }
}
