/*
Copyright 2022 The Numaproj Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Openapi Generator. DO NOT EDIT.

/// GroupBy : GroupBy indicates it is a reducer UDF

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupBy {
    #[serde(rename = "allowedLateness", skip_serializing_if = "Option::is_none")]
    pub allowed_lateness: Option<kube::core::Duration>,
    #[serde(rename = "keyed", skip_serializing_if = "Option::is_none")]
    pub keyed: Option<bool>,
    #[serde(rename = "storage", skip_serializing_if = "Option::is_none")]
    pub storage: Option<Box<crate::models::PbqStorage>>,
    #[serde(rename = "window")]
    pub window: Box<crate::models::Window>,
}

impl GroupBy {
    /// GroupBy indicates it is a reducer UDF
    pub fn new(window: crate::models::Window) -> GroupBy {
        GroupBy {
            allowed_lateness: None,
            keyed: None,
            storage: None,
            window: Box::new(window),
        }
    }
}
