/*
 * Numaflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ServingSource : ServingSource is the HTTP endpoint for Numaflow.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServingSource {
    #[serde(rename = "auth", skip_serializing_if = "Option::is_none")]
    pub auth: Option<Box<crate::models::Authorization>>,
    /// The header key from which the message id will be extracted
    #[serde(rename = "msgIDHeaderKey")]
    pub msg_id_header_key: String,
    /// Whether to create a ClusterIP Service
    #[serde(rename = "service", skip_serializing_if = "Option::is_none")]
    pub service: Option<bool>,
    #[serde(rename = "store")]
    pub store: Box<crate::models::ServingStore>,
}

impl ServingSource {
    /// ServingSource is the HTTP endpoint for Numaflow.
    pub fn new(msg_id_header_key: String, store: crate::models::ServingStore) -> ServingSource {
        ServingSource {
            auth: None,
            msg_id_header_key,
            service: None,
            store: Box::new(store),
        }
    }
}


