/*
 * Numaflow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SessionWindow : SessionWindow describes a session window



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionWindow {
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<kube::core::Duration>,
}

impl SessionWindow {
    /// SessionWindow describes a session window
    pub fn new() -> SessionWindow {
        SessionWindow {
            timeout: None,
        }
    }
}


