apiVersion: v1
kind: ConfigMap
metadata:
  name: numaflow-metrics-proxy-config
data:
  config.yaml: |
    # url: http://my-release-kube-prometheus-prometheus.default.svc.cluster.local:9090
    patterns:
    - name: mono_vertex_histogram
      object: mono-vertex
      title: Processing Time Latency
      description: This query pattern is for P99,P90 and P50 quantiles for a mono-vertex across different dimensions
      expr: |
        $function_name($args, $aggregator by($group_by_labels,le) ($inner_function($metric_name{$filter_labels}[$rangeVector])))
      metrics:
        - metric_name: monovtx_processing_time_bucket
          filter_labels:
            - namespace
            - mvtx-name
            - pod
          group_by_labels:
            - mvtx_name
            - pod
      inner_function: rate
      function:
        name: histogram_quantile
        args:
          - 0.99
          - 0.90
          - 0.50
      rangeVector: 5m
      aggregator: sum