name: docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    if: github.repository == 'numaproj/numaflow'
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: docs/package-lock.json
      - name: Install dependencies
        working-directory: docs
        run: npm ci
      - name: Build docs
        run: make docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.repository == 'numaproj/numaflow' && github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
          cname: numaflow.numaproj.io
