apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: numaflow-server-secrets-role
  labels:
    app.kubernetes.io/name: numaflow-ux
    app.kubernetes.io/part-of: numaflow
    app.kubernetes.io/component: numaflow-ux
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - update
